package sys

import (
	"context"
	"strings"
	"sync"

	"github.com/gogf/gf/v2/frame/g"

	"hotgo/internal/consts"
)

var tgChannelMemberSchemaOnce sync.Once

func ensureTgChannelMemberSchema(ctx context.Context) error {
	var err error
	tgChannelMemberSchemaOnce.Do(func() {
		if strings.ToLower(g.DB().GetConfig().Type) == consts.DBPgsql {
			_, err = g.DB().Exec(ctx, tgChannelMemberPgSQL())
			return
		}
		_, err = g.DB().Exec(ctx, tgChannelMemberMySQL())
	})
	return err
}

func tgChannelMemberPgSQL() string {
	return `
CREATE TABLE IF NOT EXISTS "hg_youban_publish_tg_channel_member" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tenant_id" bigint NOT NULL DEFAULT 0,
  "tg_account_id" bigint NOT NULL DEFAULT 0,
  "channel_id" varchar(32) NOT NULL DEFAULT '',
  "user_id" bigint NOT NULL DEFAULT 0,
  "access_hash" varchar(32) NOT NULL DEFAULT '',
  "display_name" varchar(255) NOT NULL DEFAULT '',
  "first_name" varchar(255) NOT NULL DEFAULT '',
  "last_name" varchar(255) NOT NULL DEFAULT '',
  "username" varchar(255) NOT NULL DEFAULT '',
  "phone" varchar(32) NOT NULL DEFAULT '',
  "participant_role" varchar(16) NOT NULL DEFAULT 'member',
  "is_bot" smallint NOT NULL DEFAULT 0,
  "is_premium" smallint NOT NULL DEFAULT 0,
  "status" smallint NOT NULL DEFAULT 1,
  "last_sync_task_id" bigint NOT NULL DEFAULT 0,
  "last_synced_at" timestamp NULL,
  "created_at" timestamp NULL,
  "updated_at" timestamp NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS "uk_ybp_tg_channel_member" ON "hg_youban_publish_tg_channel_member" ("tenant_id", "tg_account_id", "channel_id", "user_id");
CREATE INDEX IF NOT EXISTS "idx_ybp_tg_channel_member_query" ON "hg_youban_publish_tg_channel_member" ("tenant_id", "tg_account_id", "channel_id", "participant_role", "status", "id");
CREATE INDEX IF NOT EXISTS "idx_ybp_tg_channel_member_search" ON "hg_youban_publish_tg_channel_member" ("tenant_id", "tg_account_id", "channel_id", "display_name", "username", "user_id");

CREATE TABLE IF NOT EXISTS "hg_youban_publish_tg_channel_member_sync_task" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tenant_id" bigint NOT NULL DEFAULT 0,
  "tg_account_id" bigint NOT NULL DEFAULT 0,
  "channel_id" varchar(32) NOT NULL DEFAULT '',
  "channel_title" varchar(255) NOT NULL DEFAULT '',
  "channel_username" varchar(255) NOT NULL DEFAULT '',
  "status" varchar(16) NOT NULL DEFAULT 'pending',
  "stage" varchar(32) NOT NULL DEFAULT 'created',
  "progress_total" int NOT NULL DEFAULT 0,
  "progress_done" int NOT NULL DEFAULT 0,
  "admin_total" int NOT NULL DEFAULT 0,
  "admin_done" int NOT NULL DEFAULT 0,
  "member_total" int NOT NULL DEFAULT 0,
  "member_done" int NOT NULL DEFAULT 0,
  "upserted_count" int NOT NULL DEFAULT 0,
  "removed_count" int NOT NULL DEFAULT 0,
  "error_message" text NOT NULL DEFAULT '',
  "started_at" timestamp NULL,
  "finished_at" timestamp NULL,
  "canceled_at" timestamp NULL,
  "created_at" timestamp NULL,
  "updated_at" timestamp NULL
);
CREATE INDEX IF NOT EXISTS "idx_ybp_tg_channel_member_task_status" ON "hg_youban_publish_tg_channel_member_sync_task" ("tenant_id", "tg_account_id", "channel_id", "status", "id");
`
}

func tgChannelMemberMySQL() string {
	return `
CREATE TABLE IF NOT EXISTS hg_youban_publish_tg_channel_member (
  id bigint(20) NOT NULL AUTO_INCREMENT,
  tenant_id bigint(20) NOT NULL DEFAULT '0',
  tg_account_id bigint(20) NOT NULL DEFAULT '0',
  channel_id varchar(32) NOT NULL DEFAULT '' COMMENT '频道ID',
  user_id bigint(20) NOT NULL DEFAULT '0',
  access_hash varchar(32) NOT NULL DEFAULT '',
  display_name varchar(255) NOT NULL DEFAULT '',
  first_name varchar(255) NOT NULL DEFAULT '',
  last_name varchar(255) NOT NULL DEFAULT '',
  username varchar(255) NOT NULL DEFAULT '',
  phone varchar(32) NOT NULL DEFAULT '',
  participant_role varchar(16) NOT NULL DEFAULT 'member' COMMENT '角色',
  is_bot tinyint(1) NOT NULL DEFAULT '0',
  is_premium tinyint(1) NOT NULL DEFAULT '0',
  status tinyint(1) NOT NULL DEFAULT '1',
  last_sync_task_id bigint(20) NOT NULL DEFAULT '0',
  last_synced_at datetime DEFAULT NULL,
  created_at datetime DEFAULT NULL,
  updated_at datetime DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_ybp_tg_channel_member (tenant_id,tg_account_id,channel_id,user_id),
  KEY idx_ybp_tg_channel_member_query (tenant_id,tg_account_id,channel_id,participant_role,status,id),
  KEY idx_ybp_tg_channel_member_search (tenant_id,tg_account_id,channel_id,display_name,username,user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='TG频道成员缓存';

CREATE TABLE IF NOT EXISTS hg_youban_publish_tg_channel_member_sync_task (
  id bigint(20) NOT NULL AUTO_INCREMENT,
  tenant_id bigint(20) NOT NULL DEFAULT '0',
  tg_account_id bigint(20) NOT NULL DEFAULT '0',
  channel_id varchar(32) NOT NULL DEFAULT '' COMMENT '频道ID',
  channel_title varchar(255) NOT NULL DEFAULT '',
  channel_username varchar(255) NOT NULL DEFAULT '',
  status varchar(16) NOT NULL DEFAULT 'pending',
  stage varchar(32) NOT NULL DEFAULT 'created',
  progress_total int(11) NOT NULL DEFAULT '0',
  progress_done int(11) NOT NULL DEFAULT '0',
  admin_total int(11) NOT NULL DEFAULT '0',
  admin_done int(11) NOT NULL DEFAULT '0',
  member_total int(11) NOT NULL DEFAULT '0',
  member_done int(11) NOT NULL DEFAULT '0',
  upserted_count int(11) NOT NULL DEFAULT '0',
  removed_count int(11) NOT NULL DEFAULT '0',
  error_message text,
  started_at datetime DEFAULT NULL,
  finished_at datetime DEFAULT NULL,
  canceled_at datetime DEFAULT NULL,
  created_at datetime DEFAULT NULL,
  updated_at datetime DEFAULT NULL,
  PRIMARY KEY (id),
  KEY idx_ybp_tg_channel_member_task_status (tenant_id,tg_account_id,channel_id,status,id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='TG频道成员同步任务';
`
}
