package service

import (
	"context"

	"hotgo/addons/youban_publish/model/input/sysin"

	"github.com/gogf/gf/v2/net/ghttp"
)

type ISysPublish interface {
	StartRuntime(ctx context.Context)
	StopRuntime()
	AdminTenantList(ctx context.Context, in *sysin.TenantListInp) (list []*sysin.TenantModel, totalCount int, err error)
	AdminTenantSave(ctx context.Context, in *sysin.TenantSaveInp) (res *sysin.TenantSaveModel, err error)
	AdminTenantDelete(ctx context.Context, in *sysin.TenantDeleteInp) (err error)
	ServerAccountList(ctx context.Context, in *sysin.AccountListInp) (list []*sysin.AccountModel, totalCount int, err error)
	ServerAccountSave(ctx context.Context, in *sysin.AccountSaveInp) (res *sysin.AccountSaveModel, err error)
	ServerAccountResetPassword(ctx context.Context, in *sysin.AccountResetPasswordInp) (res *sysin.AccountSaveModel, err error)
	ServerAccountDelete(ctx context.Context, in *sysin.AccountDeleteInp) (err error)
	ServerTaskList(ctx context.Context, in *sysin.TaskListInp) (list []*sysin.TaskModel, totalCount int, err error)
	ServerTaskSave(ctx context.Context, in *sysin.TaskSaveInp) (id int64, err error)
	ServerTaskSubmit(ctx context.Context, in *sysin.TaskSubmitInp) (err error)
	ServerTaskCancel(ctx context.Context, in *sysin.TaskCancelInp) (err error)
	ServerMediaList(ctx context.Context, in *sysin.MediaListInp) (list []*sysin.MediaModel, err error)
	ServerMediaDelete(ctx context.Context, in *sysin.MediaDeleteInp) (err error)
	ServerBotList(ctx context.Context, in *sysin.BotListInp) (list []*sysin.BotModel, totalCount int, err error)
	ServerBotSave(ctx context.Context, in *sysin.BotSaveInp) (err error)
	ServerBotDelete(ctx context.Context, in *sysin.BotDeleteInp) (err error)
	ServerBotRefresh(ctx context.Context, in *sysin.BotRefreshInp) (list []*sysin.BotRefreshModel, err error)
	ServerTgAccountList(ctx context.Context, in *sysin.TgAccountListInp) (list []*sysin.TgAccountModel, totalCount int, err error)
	ServerTgAccountDelete(ctx context.Context, in *sysin.TgAccountDeleteInp) (err error)
	ServerTgAccountRefresh(ctx context.Context, in *sysin.TgAccountRefreshInp) (list []*sysin.TgAccountRefreshModel, err error)
	ServerChannelList(ctx context.Context, in *sysin.ChannelListInp) (list []*sysin.ChannelModel, totalCount int, err error)
	ServerChannelDelete(ctx context.Context, in *sysin.ChannelDeleteInp) (err error)
	ServerChannelRefresh(ctx context.Context, in *sysin.ChannelRefreshInp) (list []*sysin.ChannelRefreshModel, err error)
	AdminAccountList(ctx context.Context, in *sysin.AccountListInp) (list []*sysin.AccountModel, totalCount int, err error)
	AdminAccountSave(ctx context.Context, in *sysin.AccountSaveInp) (res *sysin.AccountSaveModel, err error)
	AdminAccountResetPassword(ctx context.Context, in *sysin.AccountResetPasswordInp) (res *sysin.AccountSaveModel, err error)
	AdminAccountDelete(ctx context.Context, in *sysin.AccountDeleteInp) (err error)
	AdminTaskList(ctx context.Context, in *sysin.TaskListInp) (list []*sysin.TaskModel, totalCount int, err error)
	AdminTaskSave(ctx context.Context, in *sysin.TaskSaveInp) (id int64, err error)
	AdminTaskSubmit(ctx context.Context, in *sysin.TaskSubmitInp) (err error)
	AdminTaskCancel(ctx context.Context, in *sysin.TaskCancelInp) (err error)
	AdminMediaList(ctx context.Context, in *sysin.MediaListInp) (list []*sysin.MediaModel, err error)
	AdminMediaDelete(ctx context.Context, in *sysin.MediaDeleteInp) (err error)
	ServerTagSave(ctx context.Context, in *sysin.TagSaveInp) (err error)
	ServerTagDelete(ctx context.Context, in *sysin.TagDeleteInp) (err error)
	AdminBotList(ctx context.Context, in *sysin.BotListInp) (list []*sysin.BotModel, totalCount int, err error)
	AdminBotSave(ctx context.Context, in *sysin.BotSaveInp) (err error)
	AdminBotDelete(ctx context.Context, in *sysin.BotDeleteInp) (err error)
	AdminBotRefresh(ctx context.Context, in *sysin.BotRefreshInp) (list []*sysin.BotRefreshModel, err error)
	AdminTgAccountList(ctx context.Context, in *sysin.TgAccountListInp) (list []*sysin.TgAccountModel, totalCount int, err error)
	AdminTgAccountStartLogin(ctx context.Context, in *sysin.TgAccountStartLoginInp) (res *sysin.TgAccountModel, err error)
	AdminTgAccountLoginStatus(ctx context.Context, in *sysin.TgAccountLoginStatusInp) (res *sysin.TgAccountModel, err error)
	AdminTgAccountPassword(ctx context.Context, in *sysin.TgAccountPasswordInp) (res *sysin.TgAccountModel, err error)
	AdminTgAccountDelete(ctx context.Context, in *sysin.TgAccountDeleteInp) (err error)
	AdminTgAccountRefresh(ctx context.Context, in *sysin.TgAccountRefreshInp) (list []*sysin.TgAccountRefreshModel, err error)
	AdminChannelList(ctx context.Context, in *sysin.ChannelListInp) (list []*sysin.ChannelModel, totalCount int, err error)
	AdminChannelSave(ctx context.Context, in *sysin.ChannelSaveInp) (err error)
	AdminChannelCacheList(ctx context.Context, in *sysin.ChannelCacheListInp) (list []*sysin.ChannelCacheModel, totalCount int, err error)
	AdminChannelCacheRefresh(ctx context.Context, in *sysin.ChannelCacheRefreshInp) (res *sysin.ChannelCacheRefreshModel, err error)
	AdminChannelCheck(ctx context.Context, in *sysin.ChannelCheckInp) (res *sysin.ChannelCheckModel, err error)
	AdminChannelDelete(ctx context.Context, in *sysin.ChannelDeleteInp) (err error)
	AdminChannelBatchBots(ctx context.Context, in *sysin.ChannelBatchBotsInp) (err error)
	AdminChannelRefresh(ctx context.Context, in *sysin.ChannelRefreshInp) (list []*sysin.ChannelRefreshModel, err error)
	AccountLogin(ctx context.Context, in *sysin.AccountLoginInp) (res *sysin.AccountLoginModel, err error)
	AccountRegister(ctx context.Context, in *sysin.AccountRegisterInp) (res *sysin.AccountRegisterModel, err error)
	CurrentAccount(ctx context.Context) (res *sysin.CurrentAccountModel, err error)
	UpdateAccountPassword(ctx context.Context, in *sysin.UpdateAccountPasswordInp) (err error)
	UpdateAccountProfile(ctx context.Context, in *sysin.UpdateAccountProfileInp) (res *sysin.CurrentAccountModel, err error)
	MyProfileList(ctx context.Context, in *sysin.ProfileListInp) (list []*sysin.ProfileModel, totalCount int, err error)
	MyChannelList(ctx context.Context, in *sysin.ChannelListInp) (list []*sysin.ChannelModel, totalCount int, err error)
	MyProfileView(ctx context.Context, in *sysin.ProfileViewInp) (res *sysin.ProfileViewModel, err error)
	MyProfileOptions(ctx context.Context) (res *sysin.ProfileOptionsModel, err error)
	MyProfileSave(ctx context.Context, in *sysin.ProfileSaveInp) (res *sysin.ProfileSaveModel, err error)
	MyProfileDelete(ctx context.Context, in *sysin.ProfileDeleteInp) (err error)
	MyProfileStatus(ctx context.Context, in *sysin.ProfileStatusInp) (err error)
	MyProfileImageSearch(ctx context.Context, in *sysin.ProfileImageSearchInp, file *ghttp.UploadFile) (list []*sysin.NoteModel, totalCount int, err error)
	MyNoteList(ctx context.Context, in *sysin.NoteListInp) (list []*sysin.NoteModel, totalCount int, err error)
	MyTagList(ctx context.Context, in *sysin.TagListInp) (list []*sysin.TagModel, totalCount int, err error)
	MyTagSave(ctx context.Context, in *sysin.TagSaveInp) (err error)
	MyTagDelete(ctx context.Context, in *sysin.TagDeleteInp) (err error)
	MyCityForward(ctx context.Context, in *sysin.CityForwardInp) (res *sysin.CityForwardModel, err error)
	MyProfileStats(ctx context.Context, in *sysin.TrendInp) (res *sysin.ProfileStatsModel, err error)
	AdminProfileList(ctx context.Context, in *sysin.ProfileListInp) (list []*sysin.ProfileModel, totalCount int, err error)
	AdminProfileSave(ctx context.Context, in *sysin.ProfileSaveInp) (res *sysin.ProfileSaveModel, err error)
	AdminProfileDelete(ctx context.Context, in *sysin.ProfileDeleteInp) (err error)
	AdminProfileStatus(ctx context.Context, in *sysin.ProfileStatusInp) (err error)
	AdminNoteList(ctx context.Context, in *sysin.NoteListInp) (list []*sysin.NoteModel, totalCount int, err error)
	AdminTagList(ctx context.Context, in *sysin.TagListInp) (list []*sysin.TagModel, totalCount int, err error)
	AdminTagSave(ctx context.Context, in *sysin.TagSaveInp) (err error)
	AdminTagDelete(ctx context.Context, in *sysin.TagDeleteInp) (err error)
	AdminCityForward(ctx context.Context, in *sysin.CityForwardInp) (res *sysin.CityForwardModel, err error)
	AdminProfileStats(ctx context.Context, in *sysin.TrendInp) (res *sysin.ProfileStatsModel, err error)
	MyTaskList(ctx context.Context, in *sysin.TaskListInp) (list []*sysin.TaskModel, totalCount int, err error)
	MyTaskSave(ctx context.Context, in *sysin.TaskSaveInp) (id int64, err error)
	MyTaskSubmit(ctx context.Context, in *sysin.TaskSubmitInp) (err error)
	MyTaskCancel(ctx context.Context, in *sysin.TaskCancelInp) (err error)
	MyMediaUpload(ctx context.Context, in *sysin.MediaUploadInp, file *ghttp.UploadFile) (res *sysin.MediaModel, err error)
	MyMediaList(ctx context.Context, in *sysin.MediaListInp) (list []*sysin.MediaModel, err error)
	MyMediaDelete(ctx context.Context, in *sysin.MediaDeleteInp) (err error)
	MyMediaSort(ctx context.Context, in *sysin.MediaSortInp) (err error)
	TelegramWebhookRaw(ctx context.Context, botId int64, body []byte) (err error)
	TelegramLoginStart(ctx context.Context, in *sysin.TelegramLoginStartInp) (res *sysin.TelegramLoginModel, err error)
	TelegramLoginStatus(ctx context.Context, in *sysin.TelegramLoginStatusInp) (res *sysin.TelegramLoginModel, err error)
	TelegramLoginPassword(ctx context.Context, in *sysin.TelegramLoginPasswordInp) (res *sysin.TelegramLoginModel, err error)
}

var localSysPublish ISysPublish

func SysPublish() ISysPublish {
	if localSysPublish == nil {
		panic("implement not found for interface ISysPublish, forgot register?")
	}
	return localSysPublish
}

func RegisterSysPublish(i ISysPublish) {
	localSysPublish = i
}
