package service

import (
	"context"

	"hotgo/addons/youban_publish/model/input/sysin"
	basesysin "hotgo/internal/model/input/sysin"

	"github.com/gogf/gf/v2/net/ghttp"
)

type ISysPublish interface {
	StartRuntime(ctx context.Context)
	StopRuntime()
	AdminTenantList(ctx context.Context, in *sysin.TenantListInp) (list []*sysin.TenantModel, totalCount int, err error)
	AdminTenantSave(ctx context.Context, in *sysin.TenantSaveInp) (res *sysin.TenantSaveModel, err error)
	AdminTenantDelete(ctx context.Context, in *sysin.TenantDeleteInp) (err error)
	ServerAccountList(ctx context.Context, in *sysin.AccountListInp) (list []*sysin.AccountModel, totalCount int, err error)
	ServerAccountSave(ctx context.Context, in *sysin.AccountSaveInp) (res *sysin.AccountSaveModel, err error)
	ServerAccountResetPassword(ctx context.Context, in *sysin.AccountResetPasswordInp) (res *sysin.AccountSaveModel, err error)
	ServerAccountDelete(ctx context.Context, in *sysin.AccountDeleteInp) (err error)
	ServerTaskList(ctx context.Context, in *sysin.TaskListInp) (list []*sysin.TaskModel, totalCount int, err error)
	ServerTaskSave(ctx context.Context, in *sysin.TaskSaveInp) (id int64, err error)
	ServerTaskSubmit(ctx context.Context, in *sysin.TaskSubmitInp) (err error)
	ServerTaskCancel(ctx context.Context, in *sysin.TaskCancelInp) (err error)
	ServerProfileList(ctx context.Context, in *sysin.ProfileListInp) (list []*sysin.ProfileModel, totalCount int, err error)
	ServerProfileView(ctx context.Context, in *sysin.ProfileViewInp) (res *sysin.ProfileViewModel, err error)
	ServerProfileSave(ctx context.Context, in *sysin.ProfileSaveInp) (res *sysin.ProfileSaveModel, err error)
	ServerProfileDelete(ctx context.Context, in *sysin.ProfileDeleteInp) (err error)
	ServerProfileReview(ctx context.Context, in *sysin.ProfileReviewInp) (err error)
	ServerImportTaskList(ctx context.Context, in *sysin.ImportTaskListInp) (list []*sysin.ImportTaskModel, totalCount int, err error)
	ServerImportTaskCreate(ctx context.Context, in *sysin.ImportTaskCreateInp) (id int64, err error)
	ServerImportTaskView(ctx context.Context, in *sysin.ImportTaskViewInp) (res *sysin.ImportTaskModel, err error)
	ServerImportTaskStart(ctx context.Context, in *sysin.ImportTaskActionInp) (err error)
	ServerImportTaskCancel(ctx context.Context, in *sysin.ImportTaskActionInp) (err error)
	ServerImportTaskRetry(ctx context.Context, in *sysin.ImportTaskActionInp) (err error)
	ServerImportTaskScan(ctx context.Context, in *sysin.ImportTaskScanInp) (res *sysin.ImportTaskScanModel, err error)
	ServerImportTaskRepair(ctx context.Context, in *sysin.ImportTaskRepairInp) (err error)
	ServerImportRunList(ctx context.Context, in *sysin.ImportRunListInp) (list []*sysin.ImportRunModel, totalCount int, err error)
	ServerImportRunCreate(ctx context.Context, in *sysin.ImportRunCreateInp) (id int64, err error)
	ServerImportRunDelete(ctx context.Context, in *sysin.ImportRunActionInp) (err error)
	ServerImportRunCancel(ctx context.Context, in *sysin.ImportRunActionInp) (err error)
	ServerImportRunLogList(ctx context.Context, in *sysin.ImportRunLogListInp) (list []*sysin.ImportRunLogModel, totalCount int, err error)
	ServerImportRunLogClear(ctx context.Context, in *sysin.ImportRunActionInp) (err error)
	ServerImportRunMatchConfig(ctx context.Context, in *sysin.ImportRunMatchConfigInp) (res *sysin.ImportRunMatchConfigModel, err error)
	ServerImportRunMatchStart(ctx context.Context, in *sysin.ImportRunMatchStartInp) (res *sysin.ImportRunMatchRunModel, err error)
	ServerImportRunTgSyncStart(ctx context.Context, in *sysin.ImportRunTgSyncStartInp) (res *sysin.ImportRunMatchRunModel, err error)
	ServerImportRunMatchView(ctx context.Context, in *sysin.ImportRunMatchViewInp) (res *sysin.ImportRunMatchRunModel, err error)
	ServerImportRunMatchItemList(ctx context.Context, in *sysin.ImportRunMatchItemListInp) (list []*sysin.ImportRunMatchItemModel, totalCount int, err error)
	ServerImportRunMatchCandidateList(ctx context.Context, in *sysin.ImportRunMatchCandidateListInp) (list []*sysin.ImportRunMatchCandidateModel, err error)
	ServerImportRunMatchCandidateSearch(ctx context.Context, in *sysin.ImportRunMatchCandidateSearchInp) (list []*sysin.ImportRunMatchCandidateModel, totalCount int, err error)
	ServerImportRunMatchSaveDraft(ctx context.Context, in *sysin.ImportRunMatchSaveDraftInp) (err error)
	ServerImportRunMatchConfirm(ctx context.Context, in *sysin.ImportRunMatchConfirmInp) (err error)
	ServerImportRunMatchBatchConfirm(ctx context.Context, in *sysin.ImportRunMatchBatchConfirmInp) (err error)
	ServerImportRunMatchSkip(ctx context.Context, in *sysin.ImportRunMatchSkipInp) (err error)
	ServerImportRunMatchUnbind(ctx context.Context, in *sysin.ImportRunMatchUnbindInp) (err error)
	ServerMediaList(ctx context.Context, in *sysin.MediaListInp) (list []*sysin.MediaModel, err error)
	ServerMediaDelete(ctx context.Context, in *sysin.MediaDeleteInp) (err error)
	ServerBotList(ctx context.Context, in *sysin.BotListInp) (list []*sysin.BotModel, totalCount int, err error)
	ServerBotSave(ctx context.Context, in *sysin.BotSaveInp) (err error)
	ServerBotDelete(ctx context.Context, in *sysin.BotDeleteInp) (err error)
	ServerBotRefresh(ctx context.Context, in *sysin.BotRefreshInp) (list []*sysin.BotRefreshModel, err error)
	ServerTgAccountList(ctx context.Context, in *sysin.TgAccountListInp) (list []*sysin.TgAccountModel, totalCount int, err error)
	ServerTgAccountDelete(ctx context.Context, in *sysin.TgAccountDeleteInp) (err error)
	ServerTgAccountRefresh(ctx context.Context, in *sysin.TgAccountRefreshInp) (list []*sysin.TgAccountRefreshModel, err error)
	ServerChannelList(ctx context.Context, in *sysin.ChannelListInp) (list []*sysin.ChannelModel, totalCount int, err error)
	ServerChannelDelete(ctx context.Context, in *sysin.ChannelDeleteInp) (err error)
	ServerChannelRefresh(ctx context.Context, in *sysin.ChannelRefreshInp) (list []*sysin.ChannelRefreshModel, err error)
	ServerDashboard(ctx context.Context, in *sysin.TrendInp) (res *sysin.ServerDashboardModel, err error)
	AdminAccountList(ctx context.Context, in *sysin.AccountListInp) (list []*sysin.AccountModel, totalCount int, err error)
	AdminAccountSave(ctx context.Context, in *sysin.AccountSaveInp) (res *sysin.AccountSaveModel, err error)
	AdminAccountResetPassword(ctx context.Context, in *sysin.AccountResetPasswordInp) (res *sysin.AccountSaveModel, err error)
	AdminAccountDelete(ctx context.Context, in *sysin.AccountDeleteInp) (err error)
	AdminAccountSettingView(ctx context.Context, in *sysin.AccountSettingViewInp) (res *sysin.AccountSettingModel, err error)
	AdminAccountSettingSave(ctx context.Context, in *sysin.AccountSettingSaveInp) (res *sysin.AccountSettingModel, err error)
	AdminDashboardOverview(ctx context.Context) (res *sysin.DashboardOverviewModel, err error)
	AdminDashboardTrend(ctx context.Context, in *sysin.TrendInp) (res *sysin.DashboardTrendModel, err error)
	AdminDashboardTodo(ctx context.Context) (res *sysin.DashboardTodoModel, err error)
	AdminDashboardRank(ctx context.Context) (res *sysin.DashboardRankModel, err error)
	AdminTaskList(ctx context.Context, in *sysin.TaskListInp) (list []*sysin.TaskModel, totalCount int, err error)
	AdminTaskSave(ctx context.Context, in *sysin.TaskSaveInp) (id int64, err error)
	AdminTaskSubmit(ctx context.Context, in *sysin.TaskSubmitInp) (err error)
	AdminTaskCancel(ctx context.Context, in *sysin.TaskCancelInp) (err error)
	AdminImportTaskList(ctx context.Context, in *sysin.ImportTaskListInp) (list []*sysin.ImportTaskModel, totalCount int, err error)
	AdminImportTaskCreate(ctx context.Context, in *sysin.ImportTaskCreateInp) (id int64, err error)
	AdminImportTaskView(ctx context.Context, in *sysin.ImportTaskViewInp) (res *sysin.ImportTaskModel, err error)
	AdminImportTaskStart(ctx context.Context, in *sysin.ImportTaskActionInp) (err error)
	AdminImportTaskCancel(ctx context.Context, in *sysin.ImportTaskActionInp) (err error)
	AdminImportTaskRetry(ctx context.Context, in *sysin.ImportTaskActionInp) (err error)
	AdminMediaList(ctx context.Context, in *sysin.MediaListInp) (list []*sysin.MediaModel, err error)
	AdminMediaUpload(ctx context.Context, in *sysin.MediaUploadInp, file *ghttp.UploadFile, poster *ghttp.UploadFile, originalFile *ghttp.UploadFile) (res *sysin.MediaModel, err error)
	AdminMediaDelete(ctx context.Context, in *sysin.MediaDeleteInp) (err error)
	AdminMediaSort(ctx context.Context, in *sysin.MediaSortInp) (err error)
	AdminAntiScanPreview(ctx context.Context, in *sysin.AntiScanPreviewInp, file *ghttp.UploadFile) (res *sysin.AntiScanPreviewModel, err error)
	AdminAntiScanMaterialList(ctx context.Context, in *sysin.AntiScanMaterialListInp) (list []*sysin.AntiScanMaterialModel, err error)
	AdminAntiScanMaterialUpload(ctx context.Context, in *sysin.AntiScanMaterialUploadInp, file *ghttp.UploadFile) (res *sysin.AntiScanMaterialModel, err error)
	ServerTagSave(ctx context.Context, in *sysin.TagSaveInp) (err error)
	ServerTagDelete(ctx context.Context, in *sysin.TagDeleteInp) (err error)
	AdminBotList(ctx context.Context, in *sysin.BotListInp) (list []*sysin.BotModel, totalCount int, err error)
	AdminBotSave(ctx context.Context, in *sysin.BotSaveInp) (err error)
	AdminBotDelete(ctx context.Context, in *sysin.BotDeleteInp) (err error)
	AdminBotRefresh(ctx context.Context, in *sysin.BotRefreshInp) (list []*sysin.BotRefreshModel, err error)
	AdminTgAccountList(ctx context.Context, in *sysin.TgAccountListInp) (list []*sysin.TgAccountModel, totalCount int, err error)
	AdminTgAccountStartLogin(ctx context.Context, in *sysin.TgAccountStartLoginInp) (res *sysin.TgAccountModel, err error)
	AdminTgAccountLoginStatus(ctx context.Context, in *sysin.TgAccountLoginStatusInp) (res *sysin.TgAccountModel, err error)
	AdminTgAccountPassword(ctx context.Context, in *sysin.TgAccountPasswordInp) (res *sysin.TgAccountModel, err error)
	AdminTgAccountDelete(ctx context.Context, in *sysin.TgAccountDeleteInp) (err error)
	AdminTgAccountRefresh(ctx context.Context, in *sysin.TgAccountRefreshInp) (list []*sysin.TgAccountRefreshModel, err error)
	AdminChannelList(ctx context.Context, in *sysin.ChannelListInp) (list []*sysin.ChannelModel, totalCount int, err error)
	AdminChannelSave(ctx context.Context, in *sysin.ChannelSaveInp) (err error)
	AdminChannelCacheList(ctx context.Context, in *sysin.ChannelCacheListInp) (list []*sysin.ChannelCacheModel, totalCount int, err error)
	AdminChannelCacheRefresh(ctx context.Context, in *sysin.ChannelCacheRefreshInp) (res *sysin.ChannelCacheRefreshModel, err error)
	AdminChannelCheck(ctx context.Context, in *sysin.ChannelCheckInp) (res *sysin.ChannelCheckModel, err error)
	AdminChannelDelete(ctx context.Context, in *sysin.ChannelDeleteInp) (err error)
	AdminChannelBatchBots(ctx context.Context, in *sysin.ChannelBatchBotsInp) (err error)
	AdminChannelRefresh(ctx context.Context, in *sysin.ChannelRefreshInp) (list []*sysin.ChannelRefreshModel, err error)
	AdminChannelFullPush(ctx context.Context, in *sysin.ChannelFullPushInp) (res *sysin.ChannelFullPushModel, err error)
	AccountLogin(ctx context.Context, in *sysin.AccountLoginInp) (res *sysin.AccountLoginModel, err error)
	AccountRegister(ctx context.Context, in *sysin.AccountRegisterInp) (res *sysin.AccountRegisterModel, err error)
	CurrentAccount(ctx context.Context) (res *sysin.CurrentAccountModel, err error)
	MyAccountSettingView(ctx context.Context) (res *sysin.AccountSettingModel, err error)
	MyDashboardOverview(ctx context.Context) (res *sysin.DashboardOverviewModel, err error)
	MyDashboardTrend(ctx context.Context, in *sysin.TrendInp) (res *sysin.DashboardTrendModel, err error)
	MyDashboardTodo(ctx context.Context) (res *sysin.DashboardTodoModel, err error)
	UpdateAccountPassword(ctx context.Context, in *sysin.UpdateAccountPasswordInp) (err error)
	UpdateAccountProfile(ctx context.Context, in *sysin.UpdateAccountProfileInp) (res *sysin.CurrentAccountModel, err error)
	MyAccountImageUpload(ctx context.Context, file *ghttp.UploadFile) (res *basesysin.AttachmentListModel, err error)
	MyProfileList(ctx context.Context, in *sysin.ProfileListInp) (list []*sysin.ProfileModel, totalCount int, err error)
	MyChannelList(ctx context.Context, in *sysin.ChannelListInp) (list []*sysin.ChannelModel, totalCount int, err error)
	MyProfileView(ctx context.Context, in *sysin.ProfileViewInp) (res *sysin.ProfileViewModel, err error)
	MyProfileOptions(ctx context.Context) (res *sysin.ProfileOptionsModel, err error)
	MyProfileSave(ctx context.Context, in *sysin.ProfileSaveInp) (res *sysin.ProfileSaveModel, err error)
	MyProfileDelete(ctx context.Context, in *sysin.ProfileDeleteInp) (err error)
	MyProfileStatus(ctx context.Context, in *sysin.ProfileStatusInp) (res *sysin.ProfileStatusModel, err error)
	MyTgMessageRepairStart(ctx context.Context, in *sysin.TgMessageRepairStartInp) (res *sysin.TgMessageRepairModel, err error)
	MyTgMessageRepairView(ctx context.Context, in *sysin.TgMessageRepairViewInp) (res *sysin.TgMessageRepairModel, err error)
	MyProfileImageSearch(ctx context.Context, in *sysin.ProfileImageSearchInp, file *ghttp.UploadFile) (list []*sysin.NoteModel, totalCount int, err error)
	MyNoteList(ctx context.Context, in *sysin.NoteListInp) (list []*sysin.NoteModel, totalCount int, err error)
	MyTagList(ctx context.Context, in *sysin.TagListInp) (list []*sysin.TagModel, totalCount int, err error)
	MyTagSave(ctx context.Context, in *sysin.TagSaveInp) (err error)
	MyTagDelete(ctx context.Context, in *sysin.TagDeleteInp) (err error)
	MyCityForward(ctx context.Context, in *sysin.CityForwardInp) (res *sysin.CityForwardModel, err error)
	MyProfileStats(ctx context.Context, in *sysin.TrendInp) (res *sysin.ProfileStatsModel, err error)
	AdminProfileList(ctx context.Context, in *sysin.ProfileListInp) (list []*sysin.ProfileModel, totalCount int, err error)
	AdminProfileView(ctx context.Context, in *sysin.ProfileViewInp) (res *sysin.ProfileViewModel, err error)
	AdminProfileSave(ctx context.Context, in *sysin.ProfileSaveInp) (res *sysin.ProfileSaveModel, err error)
	AdminProfileDelete(ctx context.Context, in *sysin.ProfileDeleteInp) (err error)
	AdminProfileStatus(ctx context.Context, in *sysin.ProfileStatusInp) (res *sysin.ProfileStatusModel, err error)
	AdminTgMessageRepairStart(ctx context.Context, in *sysin.TgMessageRepairStartInp) (res *sysin.TgMessageRepairModel, err error)
	AdminTgMessageRepairView(ctx context.Context, in *sysin.TgMessageRepairViewInp) (res *sysin.TgMessageRepairModel, err error)
	AdminNoteList(ctx context.Context, in *sysin.NoteListInp) (list []*sysin.NoteModel, totalCount int, err error)
	AdminTagList(ctx context.Context, in *sysin.TagListInp) (list []*sysin.TagModel, totalCount int, err error)
	AdminTagSave(ctx context.Context, in *sysin.TagSaveInp) (err error)
	AdminTagDelete(ctx context.Context, in *sysin.TagDeleteInp) (err error)
	AdminCityForward(ctx context.Context, in *sysin.CityForwardInp) (res *sysin.CityForwardModel, err error)
	AdminProfileStats(ctx context.Context, in *sysin.TrendInp) (res *sysin.ProfileStatsModel, err error)
	AdminDevPublishChainTest(ctx context.Context, in *sysin.DevPublishChainTestInp) (res *sysin.DevPublishChainTestModel, err error)
	AdminPublishRecordList(ctx context.Context, in *sysin.PublishRecordListInp) (list []*sysin.PublishRecordModel, totalCount int, err error)
	AdminPublishRecordClear(ctx context.Context, in *sysin.PublishRecordClearInp) (err error)
	AdminTgObserveQueueList(ctx context.Context, in *sysin.TgObserveQueueListInp) (list []*sysin.TgObserveQueueStatModel, totalCount int, err error)
	AdminTgObserveChannelList(ctx context.Context, in *sysin.TgObserveChannelListInp) (list []*sysin.TgObserveChannelStatModel, totalCount int, err error)
	AdminTgObserveBotList(ctx context.Context, in *sysin.TgObserveBotListInp) (list []*sysin.TgObserveBotStatModel, totalCount int, err error)
	MyDevPublishChainTest(ctx context.Context, in *sysin.DevPublishChainTestInp) (res *sysin.DevPublishChainTestModel, err error)
	MyTaskList(ctx context.Context, in *sysin.TaskListInp) (list []*sysin.TaskModel, totalCount int, err error)
	MyTaskSave(ctx context.Context, in *sysin.TaskSaveInp) (id int64, err error)
	MyTaskSubmit(ctx context.Context, in *sysin.TaskSubmitInp) (err error)
	MyTaskCancel(ctx context.Context, in *sysin.TaskCancelInp) (err error)
	MyImportTaskList(ctx context.Context, in *sysin.ImportTaskListInp) (list []*sysin.ImportTaskModel, totalCount int, err error)
	MyImportTaskView(ctx context.Context, in *sysin.ImportTaskViewInp) (res *sysin.ImportTaskModel, err error)
	MyImportRunList(ctx context.Context, in *sysin.ImportRunListInp) (list []*sysin.ImportRunModel, totalCount int, err error)
	MyImportRunLogList(ctx context.Context, in *sysin.ImportRunLogListInp) (list []*sysin.ImportRunLogModel, totalCount int, err error)
	MyPublishRecordList(ctx context.Context, in *sysin.PublishRecordListInp) (list []*sysin.PublishRecordModel, totalCount int, err error)
	MyPublishRecordClear(ctx context.Context, in *sysin.PublishRecordClearInp) (err error)
	CollectConfig(ctx context.Context) (res *sysin.CollectConfigModel, err error)
	CollectConfigSave(ctx context.Context, in *sysin.CollectConfigSaveInp) (err error)
	CollectStats(ctx context.Context) (res *sysin.CollectStatsModel, err error)
	CollectSourceList(ctx context.Context, in *sysin.CollectSourceListInp) (list []*sysin.CollectSourceModel, totalCount int, err error)
	CollectSourceSave(ctx context.Context, in *sysin.CollectSourceSaveInp) (id int64, err error)
	CollectSourceDelete(ctx context.Context, in *sysin.IdsInp) (err error)
	CollectSourceStatus(ctx context.Context, in *sysin.CollectStatusInp) (err error)
	CollectSourceDown(ctx context.Context, in *sysin.CollectSourceDownInp) (err error)
	CollectSourceHistoryStart(ctx context.Context, in *sysin.CollectSourceHistoryStartInp) (res *sysin.CollectHistoryTaskModel, err error)
	CollectHistoryTaskList(ctx context.Context, in *sysin.CollectHistoryTaskListInp) (list []*sysin.CollectHistoryTaskModel, totalCount int, err error)
	CollectHistoryLogList(ctx context.Context, in *sysin.CollectHistoryLogListInp) (list []*sysin.CollectHistoryLogModel, totalCount int, err error)
	CollectRuleList(ctx context.Context, in *sysin.CollectRuleListInp) (list []*sysin.CollectRuleModel, totalCount int, err error)
	CollectRuleSave(ctx context.Context, in *sysin.CollectRuleSaveInp) (id int64, err error)
	CollectRuleDelete(ctx context.Context, in *sysin.IdsInp) (err error)
	CollectEventList(ctx context.Context, in *sysin.CollectEventListInp) (list []*sysin.CollectEventModel, totalCount int, err error)
	CollectEventClear(ctx context.Context, in *sysin.CollectEventClearInp) (err error)
	CollectEventProcess(ctx context.Context, in *sysin.CollectEventProcessInp) (err error)
	CollectContentList(ctx context.Context, in *sysin.CollectContentListInp) (list []*sysin.CollectContentModel, totalCount int, err error)
	CollectContentView(ctx context.Context, in *sysin.CollectContentViewInp) (res *sysin.CollectContentModel, err error)
	CollectReviewList(ctx context.Context, in *sysin.CollectReviewListInp) (list []*sysin.CollectReviewModel, totalCount int, err error)
	CollectReviewAction(ctx context.Context, in *sysin.CollectReviewActionInp) (err error)
	AccountProfileView(ctx context.Context, in *sysin.AccountProfileViewInp) (res *sysin.AccountProfileModel, err error)
	AccountProfileSave(ctx context.Context, in *sysin.AccountProfileSaveInp) (res *sysin.AccountProfileModel, err error)
	AccountFollowList(ctx context.Context, in *sysin.AccountFollowListInp) (list []*sysin.AccountFollowModel, totalCount int, err error)
	AccountFollowApply(ctx context.Context, in *sysin.AccountFollowApplyInp) (err error)
	AccountFollowAction(ctx context.Context, in *sysin.AccountFollowActionInp) (err error)
	FollowNoteList(ctx context.Context, in *sysin.FollowNoteListInp) (list []*sysin.NoteModel, totalCount int, err error)
	FollowNoteView(ctx context.Context, in *sysin.ProfileViewInp) (res *sysin.ProfileViewModel, err error)
	FollowNoteImageSearch(ctx context.Context, in *sysin.FollowNoteListInp, file *ghttp.UploadFile) (list []*sysin.NoteModel, totalCount int, err error)
	ExecuteImportTask(ctx context.Context, id int64) (err error)
	MyMediaUpload(ctx context.Context, in *sysin.MediaUploadInp, file *ghttp.UploadFile, poster *ghttp.UploadFile, originalFile *ghttp.UploadFile) (res *sysin.MediaModel, err error)
	MyMediaList(ctx context.Context, in *sysin.MediaListInp) (list []*sysin.MediaModel, err error)
	MyMediaDelete(ctx context.Context, in *sysin.MediaDeleteInp) (err error)
	MyMediaSort(ctx context.Context, in *sysin.MediaSortInp) (err error)
	TelegramWebhookRaw(ctx context.Context, botId int64, body []byte) (err error)
	TelegramLoginStart(ctx context.Context, in *sysin.TelegramLoginStartInp) (res *sysin.TelegramLoginModel, err error)
	TelegramLoginStatus(ctx context.Context, in *sysin.TelegramLoginStatusInp) (res *sysin.TelegramLoginModel, err error)
	TelegramLoginPassword(ctx context.Context, in *sysin.TelegramLoginPasswordInp) (res *sysin.TelegramLoginModel, err error)
}

var localSysPublish ISysPublish

func SysPublish() ISysPublish {
	if localSysPublish == nil {
		panic("implement not found for interface ISysPublish, forgot register?")
	}
	return localSysPublish
}

func RegisterSysPublish(i ISysPublish) {
	localSysPublish = i
}
