package service

import (
	"context"

	"hotgo/addons/youban_publish/model/input/sysin"
	basesysin "hotgo/internal/model/input/sysin"

	"github.com/gogf/gf/v2/net/ghttp"
)

type ISysPublish interface {
	TelegramRichTextHTML(value string) string
	StartRuntime(ctx context.Context)
	StopRuntime()
	RunChannelCycleScheduler(ctx context.Context) error
	AdminTenantList(ctx context.Context, in *sysin.TenantListInp) (list []*sysin.TenantModel, totalCount int, err error)
	AdminTenantSave(ctx context.Context, in *sysin.TenantSaveInp) (res *sysin.TenantSaveModel, err error)
	AdminTenantDelete(ctx context.Context, in *sysin.TenantDeleteInp) (err error)
	ServerAccountList(ctx context.Context, in *sysin.AccountListInp) (list []*sysin.AccountModel, totalCount int, err error)
	ServerAccountSave(ctx context.Context, in *sysin.AccountSaveInp) (res *sysin.AccountSaveModel, err error)
	ServerAccountResetPassword(ctx context.Context, in *sysin.AccountResetPasswordInp) (res *sysin.AccountSaveModel, err error)
	ServerAccountDelete(ctx context.Context, in *sysin.AccountDeleteInp) (err error)
	ServerTaskList(ctx context.Context, in *sysin.TaskListInp) (list []*sysin.TaskModel, totalCount int, err error)
	ServerTaskSave(ctx context.Context, in *sysin.TaskSaveInp) (id int64, err error)
	ServerTaskSubmit(ctx context.Context, in *sysin.TaskSubmitInp) (err error)
	ServerTaskCancel(ctx context.Context, in *sysin.TaskCancelInp) (err error)
	ServerProfileList(ctx context.Context, in *sysin.ProfileListInp) (list []*sysin.ProfileModel, totalCount int, err error)
	ServerProfileView(ctx context.Context, in *sysin.ProfileViewInp) (res *sysin.ProfileViewModel, err error)
	ServerProfileEdit(ctx context.Context, in *sysin.ProfileSaveInp) (res *sysin.ProfileSaveModel, err error)
	ServerProfileDelete(ctx context.Context, in *sysin.ProfileDeleteInp) (err error)
	ServerProfilePurgeDeleted(ctx context.Context, in *sysin.ProfilePurgeDeletedInp) (res *sysin.ProfilePurgeDeletedModel, err error)
	ServerProfileReview(ctx context.Context, in *sysin.ProfileReviewInp) (err error)
	ServerImportTaskList(ctx context.Context, in *sysin.ImportTaskListInp) (list []*sysin.ImportTaskModel, totalCount int, err error)
	ServerImportTaskCreate(ctx context.Context, in *sysin.ImportTaskCreateInp) (id int64, err error)
	ServerImportTaskView(ctx context.Context, in *sysin.ImportTaskViewInp) (res *sysin.ImportTaskModel, err error)
	ServerImportTaskStart(ctx context.Context, in *sysin.ImportTaskActionInp) (err error)
	ServerImportTaskCancel(ctx context.Context, in *sysin.ImportTaskActionInp) (err error)
	ServerImportTaskRetry(ctx context.Context, in *sysin.ImportTaskActionInp) (err error)
	ServerImportTaskScan(ctx context.Context, in *sysin.ImportTaskScanInp) (res *sysin.ImportTaskScanModel, err error)
	ServerImportTaskRepair(ctx context.Context, in *sysin.ImportTaskRepairInp) (err error)
	ServerImportRunList(ctx context.Context, in *sysin.ImportRunListInp) (list []*sysin.ImportRunModel, totalCount int, err error)
	ServerImportRunCreate(ctx context.Context, in *sysin.ImportRunCreateInp) (id int64, err error)
	ServerImportRunDelete(ctx context.Context, in *sysin.ImportRunActionInp) (err error)
	ServerImportRunCancel(ctx context.Context, in *sysin.ImportRunActionInp) (err error)
	ServerImportRunLogList(ctx context.Context, in *sysin.ImportRunLogListInp) (list []*sysin.ImportRunLogModel, totalCount int, err error)
	ServerImportRunLogClear(ctx context.Context, in *sysin.ImportRunActionInp) (err error)
	ServerImportRunMatchConfig(ctx context.Context, in *sysin.ImportRunMatchConfigInp) (res *sysin.ImportRunMatchConfigModel, err error)
	ServerImportRunMatchStart(ctx context.Context, in *sysin.ImportRunMatchStartInp) (res *sysin.ImportRunMatchRunModel, err error)
	ServerImportRunTgSyncStart(ctx context.Context, in *sysin.ImportRunTgSyncStartInp) (res *sysin.ImportRunMatchRunModel, err error)
	ServerImportRunMatchView(ctx context.Context, in *sysin.ImportRunMatchViewInp) (res *sysin.ImportRunMatchRunModel, err error)
	ServerImportRunMatchItemList(ctx context.Context, in *sysin.ImportRunMatchItemListInp) (list []*sysin.ImportRunMatchItemModel, totalCount int, err error)
	ServerImportRunMatchCandidateList(ctx context.Context, in *sysin.ImportRunMatchCandidateListInp) (list []*sysin.ImportRunMatchCandidateModel, err error)
	ServerImportRunMatchCandidateSearch(ctx context.Context, in *sysin.ImportRunMatchCandidateSearchInp) (list []*sysin.ImportRunMatchCandidateModel, totalCount int, err error)
	ServerImportRunMatchSaveDraft(ctx context.Context, in *sysin.ImportRunMatchSaveDraftInp) (err error)
	ServerImportRunMatchConfirm(ctx context.Context, in *sysin.ImportRunMatchConfirmInp) (err error)
	ServerImportRunMatchBatchConfirm(ctx context.Context, in *sysin.ImportRunMatchBatchConfirmInp) (err error)
	ServerImportRunMatchSkip(ctx context.Context, in *sysin.ImportRunMatchSkipInp) (err error)
	ServerImportRunMatchUnbind(ctx context.Context, in *sysin.ImportRunMatchUnbindInp) (err error)
	AdminMaterialImportTaskList(ctx context.Context, in *sysin.MaterialImportListInp) (list []*sysin.MaterialImportTaskModel, totalCount int, err error)
	AdminMaterialImportTaskCreate(ctx context.Context, in *sysin.MaterialImportTaskSaveInp) (id int64, err error)
	ServerMaterialImportTaskCreate(ctx context.Context, in *sysin.MaterialImportTaskServerCreateInp) (id int64, err error)
	AdminMaterialImportTaskView(ctx context.Context, in *sysin.MaterialImportTaskViewInp) (res *sysin.MaterialImportTaskModel, err error)
	AdminMaterialImportTaskStart(ctx context.Context, in *sysin.MaterialImportTaskActionInp) (err error)
	AdminMaterialImportTaskCancel(ctx context.Context, in *sysin.MaterialImportTaskActionInp) (err error)
	AdminMaterialImportTaskRetry(ctx context.Context, in *sysin.MaterialImportTaskActionInp) (err error)
	ServerMediaList(ctx context.Context, in *sysin.MediaListInp) (list []*sysin.MediaModel, err error)
	ServerMediaDelete(ctx context.Context, in *sysin.MediaDeleteInp) (err error)
	ServerBotList(ctx context.Context, in *sysin.BotListInp) (list []*sysin.BotModel, totalCount int, err error)
	ServerBotSave(ctx context.Context, in *sysin.BotSaveInp) (err error)
	ServerBotDelete(ctx context.Context, in *sysin.BotDeleteInp) (err error)
	ServerBotRefresh(ctx context.Context, in *sysin.BotRefreshInp) (list []*sysin.BotRefreshModel, err error)
	ServerTgAccountList(ctx context.Context, in *sysin.TgAccountListInp) (list []*sysin.TgAccountModel, totalCount int, err error)
	ServerTgAccountDelete(ctx context.Context, in *sysin.TgAccountDeleteInp) (err error)
	ServerTgAccountRefresh(ctx context.Context, in *sysin.TgAccountRefreshInp) (list []*sysin.TgAccountRefreshModel, err error)
	ServerChannelCacheList(ctx context.Context, in *sysin.ChannelCacheListInp) (list []*sysin.ChannelCacheModel, totalCount int, err error)
	ServerChannelList(ctx context.Context, in *sysin.ChannelListInp) (list []*sysin.ChannelModel, totalCount int, err error)
	ServerChannelDelete(ctx context.Context, in *sysin.ChannelDeleteInp) (err error)
	ServerChannelRefresh(ctx context.Context, in *sysin.ChannelRefreshInp) (list []*sysin.ChannelRefreshModel, err error)
	ServerDashboard(ctx context.Context, in *sysin.TrendInp) (res *sysin.ServerDashboardModel, err error)
	AdminAccountList(ctx context.Context, in *sysin.AccountListInp) (list []*sysin.AccountModel, totalCount int, err error)
	AdminAccountOptions(ctx context.Context, in *sysin.AccountOptionsInp) (list []*sysin.AccountOptionModel, err error)
	AdminAccountSave(ctx context.Context, in *sysin.AccountSaveInp) (res *sysin.AccountSaveModel, err error)
	AdminAccountResetPassword(ctx context.Context, in *sysin.AccountResetPasswordInp) (res *sysin.AccountSaveModel, err error)
	AdminAccountDelete(ctx context.Context, in *sysin.AccountDeleteInp) (err error)
	AdminAccountTransferPreview(ctx context.Context, in *sysin.AccountTransferPreviewInp) (res *sysin.AccountTransferPreviewModel, err error)
	AdminAccountTransferProfiles(ctx context.Context, in *sysin.AccountTransferProfilesInp) (res *sysin.AccountTransferProfilesModel, err error)
	AdminAccountSettingView(ctx context.Context, in *sysin.AccountSettingViewInp) (res *sysin.AccountSettingModel, err error)
	AdminAccountSettingSave(ctx context.Context, in *sysin.AccountSettingSaveInp) (res *sysin.AccountSettingModel, err error)
	AdminDashboardOverview(ctx context.Context) (res *sysin.DashboardOverviewModel, err error)
	AdminDashboardTrend(ctx context.Context, in *sysin.TrendInp) (res *sysin.DashboardTrendModel, err error)
	AdminDashboardTodo(ctx context.Context) (res *sysin.DashboardTodoModel, err error)
	AdminDashboardRank(ctx context.Context) (res *sysin.DashboardRankModel, err error)
	AdminTaskList(ctx context.Context, in *sysin.TaskListInp) (list []*sysin.TaskModel, totalCount int, err error)
	AdminTaskSave(ctx context.Context, in *sysin.TaskSaveInp) (id int64, err error)
	AdminTaskSubmit(ctx context.Context, in *sysin.TaskSubmitInp) (err error)
	AdminTaskCancel(ctx context.Context, in *sysin.TaskCancelInp) (err error)
	AdminImportTaskList(ctx context.Context, in *sysin.ImportTaskListInp) (list []*sysin.ImportTaskModel, totalCount int, err error)
	AdminImportTaskCreate(ctx context.Context, in *sysin.ImportTaskCreateInp) (id int64, err error)
	AdminImportTaskView(ctx context.Context, in *sysin.ImportTaskViewInp) (res *sysin.ImportTaskModel, err error)
	AdminImportTaskStart(ctx context.Context, in *sysin.ImportTaskActionInp) (err error)
	AdminImportTaskCancel(ctx context.Context, in *sysin.ImportTaskActionInp) (err error)
	AdminImportTaskRetry(ctx context.Context, in *sysin.ImportTaskActionInp) (err error)
	AdminMediaList(ctx context.Context, in *sysin.MediaListInp) (list []*sysin.MediaModel, err error)
	AdminMediaUpload(ctx context.Context, in *sysin.MediaUploadInp, file *ghttp.UploadFile, poster *ghttp.UploadFile, originalFile *ghttp.UploadFile) (res *sysin.MediaModel, err error)
	AdminMediaDelete(ctx context.Context, in *sysin.MediaDeleteInp) (err error)
	ProcessStoredMediaAssets(ctx context.Context, in *sysin.StoredMediaAssetsInp) (res *sysin.StoredMediaAssetsModel, err error)
	ProcessRemoteMediaAssets(ctx context.Context, in *sysin.RemoteMediaAssetsInp) (res *sysin.RemoteMediaAssetsModel, err error)
	SyncMediaPHashBucketByMediaId(ctx context.Context, mediaId int64) (err error)
	RefreshNoteIndex(ctx context.Context, profileId int64) (err error)
	AdminAntiScanPreview(ctx context.Context, in *sysin.AntiScanPreviewInp, file *ghttp.UploadFile) (res *sysin.AntiScanPreviewModel, err error)
	AdminAntiScanMaterialList(ctx context.Context, in *sysin.AntiScanMaterialListInp) (list []*sysin.AntiScanMaterialModel, err error)
	AdminAntiScanMaterialUpload(ctx context.Context, in *sysin.AntiScanMaterialUploadInp, file *ghttp.UploadFile) (res *sysin.AntiScanMaterialModel, err error)
	ServerTagSave(ctx context.Context, in *sysin.TagSaveInp) (err error)
	ServerTagDelete(ctx context.Context, in *sysin.TagDeleteInp) (err error)
	AdminBotList(ctx context.Context, in *sysin.BotListInp) (list []*sysin.BotModel, totalCount int, err error)
	AdminBotSave(ctx context.Context, in *sysin.BotSaveInp) (err error)
	AdminBotDelete(ctx context.Context, in *sysin.BotDeleteInp) (err error)
	AdminBotRefresh(ctx context.Context, in *sysin.BotRefreshInp) (list []*sysin.BotRefreshModel, err error)
	AdminTgAccountList(ctx context.Context, in *sysin.TgAccountListInp) (list []*sysin.TgAccountModel, totalCount int, err error)
	AdminTgAccountStartLogin(ctx context.Context, in *sysin.TgAccountStartLoginInp) (res *sysin.TgAccountModel, err error)
	AdminTgAccountLoginStatus(ctx context.Context, in *sysin.TgAccountLoginStatusInp) (res *sysin.TgAccountModel, err error)
	AdminTgAccountPassword(ctx context.Context, in *sysin.TgAccountPasswordInp) (res *sysin.TgAccountModel, err error)
	AdminTgAccountDelete(ctx context.Context, in *sysin.TgAccountDeleteInp) (err error)
	AdminTgAccountRefresh(ctx context.Context, in *sysin.TgAccountRefreshInp) (list []*sysin.TgAccountRefreshModel, err error)
	AdminChannelList(ctx context.Context, in *sysin.ChannelListInp) (list []*sysin.ChannelModel, totalCount int, err error)
	AdminChannelSave(ctx context.Context, in *sysin.ChannelSaveInp) (err error)
	AdminChannelCacheList(ctx context.Context, in *sysin.ChannelCacheListInp) (list []*sysin.ChannelCacheModel, totalCount int, err error)
	AdminChannelCacheResolve(ctx context.Context, in *sysin.ChannelCacheResolveInp) (list []*sysin.ChannelCacheResolveModel, err error)
	AdminChannelCacheRefresh(ctx context.Context, in *sysin.ChannelCacheRefreshInp) (res *sysin.ChannelCacheRefreshModel, err error)
	AdminChannelCheck(ctx context.Context, in *sysin.ChannelCheckInp) (res *sysin.ChannelCheckModel, err error)
	AdminChannelMemberSyncStart(ctx context.Context, in *sysin.TgChannelMemberSyncStartInp) (res *sysin.TgChannelMemberSyncModel, err error)
	AdminChannelMemberSyncView(ctx context.Context, in *sysin.TgChannelMemberSyncViewInp) (res *sysin.TgChannelMemberSyncModel, err error)
	AdminChannelMemberSyncCancel(ctx context.Context, in *sysin.TgChannelMemberSyncCancelInp) (err error)
	AdminChannelMemberList(ctx context.Context, in *sysin.TgChannelMemberListInp) (list []*sysin.TgChannelMemberModel, totalCount int, err error)
	AdminChannelMemberExport(ctx context.Context, in *sysin.TgChannelMemberListInp) (err error)
	AdminChannelDelete(ctx context.Context, in *sysin.ChannelDeleteInp) (err error)
	AdminChannelBatchBots(ctx context.Context, in *sysin.ChannelBatchBotsInp) (err error)
	AdminChannelRefresh(ctx context.Context, in *sysin.ChannelRefreshInp) (list []*sysin.ChannelRefreshModel, err error)
	AdminChannelFullPush(ctx context.Context, in *sysin.ChannelFullPushInp) (res *sysin.ChannelFullPushModel, err error)
	AdminChannelClearQueue(ctx context.Context, in *sysin.ChannelClearQueueInp) (res *sysin.ChannelClearQueueModel, err error)
	AdminChannelBackupCreate(ctx context.Context, in *sysin.ChannelBackupCreateInp) (res *sysin.ChannelBackupCreateModel, err error)
	AdminMessageTemplateList(ctx context.Context, in *sysin.MessageTemplateListInp) (list []*sysin.MessageTemplateModel, totalCount int, err error)
	AdminMessageTemplateSave(ctx context.Context, in *sysin.MessageTemplateSaveInp) (res *sysin.MessageTemplateSaveModel, err error)
	AdminMessageTemplateDelete(ctx context.Context, in *sysin.MessageTemplateDeleteInp) (err error)
	AdminMessageTemplateMediaUpload(ctx context.Context, in *sysin.MessageTemplateMediaUploadInp, file *ghttp.UploadFile, poster *ghttp.UploadFile) (res *sysin.MessageTemplateMediaModel, err error)
	AdminMessageTemplatePush(ctx context.Context, in *sysin.MessageTemplatePushInp) (res *sysin.MessageTemplatePushModel, err error)
	AdminMessagePushPlanList(ctx context.Context, in *sysin.MessagePushPlanListInp) (list []*sysin.MessagePushPlanModel, totalCount int, err error)
	AdminMessagePushPlanSave(ctx context.Context, in *sysin.MessagePushPlanSaveInp) (res *sysin.MessagePushPlanSaveModel, err error)
	AdminMessagePushPlanDelete(ctx context.Context, in *sysin.MessagePushPlanDeleteInp) (err error)
	AdminMessagePushPlanStatus(ctx context.Context, in *sysin.MessagePushPlanStatusInp) (err error)
	AdminQuickPushPlanList(ctx context.Context, in *sysin.QuickPushPlanListInp) (list []*sysin.QuickPushPlanModel, totalCount int, err error)
	AdminQuickPushPlanSave(ctx context.Context, in *sysin.QuickPushPlanSaveInp) (res *sysin.QuickPushPlanSaveModel, err error)
	AdminQuickPushPlanDelete(ctx context.Context, in *sysin.QuickPushPlanDeleteInp) (err error)
	AdminQuickPushPlanStatus(ctx context.Context, in *sysin.QuickPushPlanStatusInp) (err error)
	QuickPushBotAccount(ctx context.Context, accountId int64) (res *sysin.QuickPushBotAccountModel, err error)
	QuickPushBotPlanList(ctx context.Context, accountId int64) (list []*sysin.QuickPushPlanModel, err error)
	QuickPushExecuteByBot(ctx context.Context, in *sysin.QuickPushBotExecuteInp) (res *sysin.QuickPushBotExecuteModel, err error)
	AdminListenerPlanList(ctx context.Context, in *sysin.ListenerPlanListInp) (list []*sysin.ListenerPlanModel, totalCount int, err error)
	AdminListenerPlanSave(ctx context.Context, in *sysin.ListenerPlanSaveInp) (res *sysin.ListenerPlanSaveModel, err error)
	AdminListenerPlanDelete(ctx context.Context, in *sysin.ListenerPlanDeleteInp) (err error)
	AdminListenerPlanStatus(ctx context.Context, in *sysin.ListenerPlanStatusInp) (err error)
	AdminListenerPlanUnbind(ctx context.Context, in *sysin.ListenerPlanUnbindInp) (err error)
	HandleBotMessage(ctx context.Context, in *sysin.BotMessageInp) (handled bool, err error)
	AccountLogin(ctx context.Context, in *sysin.AccountLoginInp) (res *sysin.AccountLoginModel, err error)
	AccountRegister(ctx context.Context, in *sysin.AccountRegisterInp) (res *sysin.AccountRegisterModel, err error)
	CurrentAccount(ctx context.Context) (res *sysin.CurrentAccountModel, err error)
	TenantVipStatus(ctx context.Context) (res *sysin.TenantVipStatusModel, err error)
	TenantVipPlans(ctx context.Context) (list []*sysin.TenantVipPlanModel, err error)
	AdminTenantVipConfigView(ctx context.Context) (res *sysin.TenantVipConfigModel, err error)
	AdminTenantVipConfigSave(ctx context.Context, in *sysin.TenantVipConfigSaveInp) (err error)
	AdminTenantVipTenantSave(ctx context.Context, in *sysin.TenantVipTenantSaveInp) (err error)
	AdminTenantVipOrderList(ctx context.Context, in *sysin.TenantVipOrderListInp) (list []*sysin.TenantVipOrderModel, totalCount int, err error)
	AdminTenantVipLogList(ctx context.Context, in *sysin.TenantVipLogListInp) (list []*sysin.TenantVipLogModel, totalCount int, err error)
	AdminTenantVipCouponList(ctx context.Context, in *sysin.TenantVipCouponListInp) (list []*sysin.TenantVipCouponModel, totalCount int, err error)
	AdminTenantVipCouponSave(ctx context.Context, in *sysin.TenantVipCouponSaveInp) (err error)
	AdminTenantVipCouponStatus(ctx context.Context, in *sysin.TenantVipCouponStatusInp) (err error)
	TenantVipOrderCreate(ctx context.Context, in *sysin.TenantVipOrderCreateInp) (res *sysin.TenantVipOrderModel, err error)
	TenantVipOrderList(ctx context.Context, in *sysin.TenantVipOrderListInp) (list []*sysin.TenantVipOrderModel, totalCount int, err error)
	TenantVipOrderPay(ctx context.Context, in *sysin.TenantVipOrderPayInp) (res *sysin.TenantVipOrderModel, err error)
	TenantVipCouponCheck(ctx context.Context, in *sysin.TenantVipCouponCheckInp) (res *sysin.TenantVipCouponCheckModel, err error)
	MediaSimilarCount(ctx context.Context, in *sysin.MediaSimilarCountInp) (res *sysin.MediaSimilarCountModel, err error)
	MediaSimilarList(ctx context.Context, in *sysin.MediaSimilarListInp) (res *sysin.MediaSimilarListModel, totalCount int, err error)
	MyAccountSettingView(ctx context.Context) (res *sysin.AccountSettingModel, err error)
	MyAccountSettingSave(ctx context.Context, in *sysin.AccountSettingSaveInp) (res *sysin.AccountSettingModel, err error)
	InviteInfo(ctx context.Context) (res *sysin.InviteInfoModel, err error)
	InviteList(ctx context.Context, in *sysin.InviteListInp) (list []*sysin.InviteModel, totalCount int, err error)
	CreateInviteCode(ctx context.Context, in *sysin.InviteCreateInp) (res *sysin.InviteCreateModel, err error)
	MyDashboardOverview(ctx context.Context) (res *sysin.DashboardOverviewModel, err error)
	MyDashboardTrend(ctx context.Context, in *sysin.TrendInp) (res *sysin.DashboardTrendModel, err error)
	MyDashboardTodo(ctx context.Context) (res *sysin.DashboardTodoModel, err error)
	UpdateAccountPassword(ctx context.Context, in *sysin.UpdateAccountPasswordInp) (err error)
	UpdateAccountProfile(ctx context.Context, in *sysin.UpdateAccountProfileInp) (res *sysin.CurrentAccountModel, err error)
	MyAccountImageUpload(ctx context.Context, file *ghttp.UploadFile) (res *basesysin.AttachmentListModel, err error)
	MyProfileList(ctx context.Context, in *sysin.ProfileListInp) (list []*sysin.ProfileModel, totalCount int, err error)
	MyChannelList(ctx context.Context, in *sysin.ChannelListInp) (list []*sysin.ChannelModel, totalCount int, err error)
	MyProfileView(ctx context.Context, in *sysin.ProfileViewInp) (res *sysin.ProfileViewModel, err error)
	MyProfileOptions(ctx context.Context) (res *sysin.ProfileOptionsModel, err error)
	MyProfileCreate(ctx context.Context, in *sysin.ProfileSaveInp) (res *sysin.ProfileSaveModel, err error)
	MyProfileEdit(ctx context.Context, in *sysin.ProfileSaveInp) (res *sysin.ProfileSaveModel, err error)
	MyProfilePublish(ctx context.Context, in *sysin.ProfileViewInp) (err error)
	MyProfileDelete(ctx context.Context, in *sysin.ProfileDeleteInp) (err error)
	MyProfileStatus(ctx context.Context, in *sysin.ProfileStatusInp) (res *sysin.ProfileStatusModel, err error)
	MyTgMessageRepairStart(ctx context.Context, in *sysin.TgMessageRepairStartInp) (res *sysin.TgMessageRepairModel, err error)
	MyTgMessageRepairView(ctx context.Context, in *sysin.TgMessageRepairViewInp) (res *sysin.TgMessageRepairModel, err error)
	MyProfileImageSearch(ctx context.Context, in *sysin.ProfileImageSearchInp, file *ghttp.UploadFile) (list []*sysin.NoteModel, totalCount int, err error)
	MyNoteList(ctx context.Context, in *sysin.NoteListInp) (list []*sysin.NoteModel, totalCount int, err error)
	MyTagList(ctx context.Context, in *sysin.TagListInp) (list []*sysin.TagModel, totalCount int, err error)
	MyTagSave(ctx context.Context, in *sysin.TagSaveInp) (err error)
	MyTagDelete(ctx context.Context, in *sysin.TagDeleteInp) (err error)
	MyCityForward(ctx context.Context, in *sysin.CityForwardInp) (res *sysin.CityForwardModel, err error)
	MyProfileStats(ctx context.Context, in *sysin.TrendInp) (res *sysin.ProfileStatsModel, err error)
	BotProfileSearch(ctx context.Context, in *sysin.BotProfileSearchInp) (list []*sysin.NoteModel, totalCount int, err error)
	BotProfileImageSearch(ctx context.Context, in *sysin.BotProfileImageSearchInp) (list []*sysin.NoteModel, totalCount int, err error)
	EnsureBotMediaSearchAccess(ctx context.Context, tenantId int64) error
	BotProfileMediaSearch(ctx context.Context, in *sysin.BotMediaSearchInp) (list []*sysin.NoteModel, totalCount int, err error)
	BotProfileView(ctx context.Context, in *sysin.BotProfileViewInp) (res *sysin.NoteModel, err error)
	BotProfileStatus(ctx context.Context, in *sysin.BotProfileStatusInp) (res *sysin.ProfileStatusModel, err error)
	BotProfileCreate(ctx context.Context, in *sysin.BotProfileCreateInp) (res *sysin.ProfileSaveModel, err error)
	BotProfileEdit(ctx context.Context, in *sysin.BotProfileEditInp) (res *sysin.NoteModel, err error)
	BotProfileCancelQueue(ctx context.Context, in *sysin.BotProfileQueueCancelInp) (res *sysin.BotProfileQueueCancelModel, err error)
	BotMediaCacheFile(ctx context.Context, in *sysin.BotMediaCacheFileInp) (res *sysin.BotMediaCacheFileModel, err error)
	BotChannelList(ctx context.Context, in *sysin.ChannelListInp) (list []*sysin.ChannelModel, totalCount int, err error)
	BotChannelCycleSave(ctx context.Context, in *sysin.BotChannelCycleSaveInp) (err error)
	BotChannelFullPush(ctx context.Context, in *sysin.BotChannelActionInp) (res *sysin.ChannelFullPushModel, err error)
	BotChannelClearQueue(ctx context.Context, in *sysin.BotChannelActionInp) (res *sysin.ChannelClearQueueModel, err error)
	AdminProfileList(ctx context.Context, in *sysin.ProfileListInp) (list []*sysin.ProfileModel, totalCount int, err error)
	AdminProfileView(ctx context.Context, in *sysin.ProfileViewInp) (res *sysin.ProfileViewModel, err error)
	AdminProfileCreate(ctx context.Context, in *sysin.ProfileSaveInp) (res *sysin.ProfileSaveModel, err error)
	AdminProfileEdit(ctx context.Context, in *sysin.ProfileSaveInp) (res *sysin.ProfileSaveModel, err error)
	AdminProfilePublish(ctx context.Context, in *sysin.ProfileViewInp) (err error)
	AdminProfileDelete(ctx context.Context, in *sysin.ProfileDeleteInp) (err error)
	AdminProfileStatus(ctx context.Context, in *sysin.ProfileStatusInp) (res *sysin.ProfileStatusModel, err error)
	AdminProfileImageSearch(ctx context.Context, in *sysin.ProfileImageSearchInp, file *ghttp.UploadFile) (list []*sysin.NoteModel, totalCount int, err error)
	AdminTgMessageRepairStart(ctx context.Context, in *sysin.TgMessageRepairStartInp) (res *sysin.TgMessageRepairModel, err error)
	AdminTgMessageRepairView(ctx context.Context, in *sysin.TgMessageRepairViewInp) (res *sysin.TgMessageRepairModel, err error)
	AdminNoteList(ctx context.Context, in *sysin.NoteListInp) (res *sysin.AdminNotePageModel, err error)
	AdminTagList(ctx context.Context, in *sysin.TagListInp) (list []*sysin.TagModel, totalCount int, err error)
	AdminTagSave(ctx context.Context, in *sysin.TagSaveInp) (err error)
	AdminTagDelete(ctx context.Context, in *sysin.TagDeleteInp) (err error)
	AdminCityForward(ctx context.Context, in *sysin.CityForwardInp) (res *sysin.CityForwardModel, err error)
	AdminProfileStats(ctx context.Context, in *sysin.TrendInp) (res *sysin.ProfileStatsModel, err error)
	AdminDevPublishChainTest(ctx context.Context, in *sysin.DevPublishChainTestInp) (res *sysin.DevPublishChainTestModel, err error)
	AdminPublishRecordList(ctx context.Context, in *sysin.PublishRecordListInp) (list []*sysin.PublishRecordModel, totalCount int, err error)
	AdminPublishRecordClear(ctx context.Context, in *sysin.PublishRecordClearInp) (err error)
	AdminTgObserveQueueList(ctx context.Context, in *sysin.TgObserveQueueListInp) (list []*sysin.TgObserveQueueStatModel, totalCount int, err error)
	AdminTgObserveChannelList(ctx context.Context, in *sysin.TgObserveChannelListInp) (list []*sysin.TgObserveChannelStatModel, totalCount int, err error)
	AdminTgObserveBotList(ctx context.Context, in *sysin.TgObserveBotListInp) (list []*sysin.TgObserveBotStatModel, totalCount int, err error)
	MyDevPublishChainTest(ctx context.Context, in *sysin.DevPublishChainTestInp) (res *sysin.DevPublishChainTestModel, err error)
	MyTaskList(ctx context.Context, in *sysin.TaskListInp) (list []*sysin.TaskModel, totalCount int, err error)
	MyTaskSave(ctx context.Context, in *sysin.TaskSaveInp) (id int64, err error)
	MyTaskSubmit(ctx context.Context, in *sysin.TaskSubmitInp) (err error)
	MyTaskCancel(ctx context.Context, in *sysin.TaskCancelInp) (err error)
	MyImportTaskList(ctx context.Context, in *sysin.ImportTaskListInp) (list []*sysin.ImportTaskModel, totalCount int, err error)
	MyImportTaskView(ctx context.Context, in *sysin.ImportTaskViewInp) (res *sysin.ImportTaskModel, err error)
	MyImportRunList(ctx context.Context, in *sysin.ImportRunListInp) (list []*sysin.ImportRunModel, totalCount int, err error)
	MyImportRunLogList(ctx context.Context, in *sysin.ImportRunLogListInp) (list []*sysin.ImportRunLogModel, totalCount int, err error)
	MyPublishRecordList(ctx context.Context, in *sysin.PublishRecordListInp) (list []*sysin.PublishRecordModel, totalCount int, err error)
	MyPublishRecordClear(ctx context.Context, in *sysin.PublishRecordClearInp) (err error)
	CollectConfig(ctx context.Context) (res *sysin.CollectConfigModel, err error)
	CollectConfigSave(ctx context.Context, in *sysin.CollectConfigSaveInp) (err error)
	CollectStats(ctx context.Context) (res *sysin.CollectStatsModel, err error)
	CollectSourceList(ctx context.Context, in *sysin.CollectSourceListInp) (list []*sysin.CollectSourceModel, totalCount int, err error)
	CollectSourceSave(ctx context.Context, in *sysin.CollectSourceSaveInp) (id int64, err error)
	CollectSourceDelete(ctx context.Context, in *sysin.IdsInp) (err error)
	CollectSourceStatus(ctx context.Context, in *sysin.CollectStatusInp) (err error)
	CollectSourceDown(ctx context.Context, in *sysin.CollectSourceDownInp) (res *sysin.CollectSourceDownModel, err error)
	CollectSourceHistoryStart(ctx context.Context, in *sysin.CollectSourceHistoryStartInp) (res *sysin.CollectHistoryTaskModel, err error)
	CollectSourceTrigger(ctx context.Context, in *sysin.CollectSourceTriggerInp) (res *sysin.CollectSourceTriggerModel, err error)
	CollectSourceReset(ctx context.Context, in *sysin.CollectSourceResetInp) (res *sysin.CollectSourceResetModel, err error)
	CollectHistoryTaskList(ctx context.Context, in *sysin.CollectHistoryTaskListInp) (list []*sysin.CollectHistoryTaskModel, totalCount int, err error)
	CollectHistoryLogList(ctx context.Context, in *sysin.CollectHistoryLogListInp) (list []*sysin.CollectHistoryLogModel, totalCount int, err error)
	CollectRuleList(ctx context.Context, in *sysin.CollectRuleListInp) (list []*sysin.CollectRuleModel, totalCount int, err error)
	CollectRuleSave(ctx context.Context, in *sysin.CollectRuleSaveInp) (id int64, err error)
	CollectRuleDelete(ctx context.Context, in *sysin.IdsInp) (err error)
	CollectEventList(ctx context.Context, in *sysin.CollectEventListInp) (list []*sysin.CollectEventModel, totalCount int, err error)
	CollectEventClear(ctx context.Context, in *sysin.CollectEventClearInp) (err error)
	CollectEventProcess(ctx context.Context, in *sysin.CollectEventProcessInp) (err error)
	CollectContentList(ctx context.Context, in *sysin.CollectContentListInp) (list []*sysin.CollectContentModel, totalCount int, err error)
	CollectContentView(ctx context.Context, in *sysin.CollectContentViewInp) (res *sysin.CollectContentModel, err error)
	CollectReviewList(ctx context.Context, in *sysin.CollectReviewListInp) (list []*sysin.CollectReviewModel, totalCount int, err error)
	CollectReviewAction(ctx context.Context, in *sysin.CollectReviewActionInp) (err error)
	AccountProfileView(ctx context.Context, in *sysin.AccountProfileViewInp) (res *sysin.AccountProfileModel, err error)
	AccountProfileSave(ctx context.Context, in *sysin.AccountProfileSaveInp) (res *sysin.AccountProfileModel, err error)
	AccountFollowList(ctx context.Context, in *sysin.AccountFollowListInp) (list []*sysin.AccountFollowModel, totalCount int, err error)
	AccountFollowApply(ctx context.Context, in *sysin.AccountFollowApplyInp) (err error)
	AccountFollowAction(ctx context.Context, in *sysin.AccountFollowActionInp) (err error)
	FollowNoteList(ctx context.Context, in *sysin.FollowNoteListInp) (list []*sysin.FollowNoteModel, totalCount int, err error)
	FollowNoteView(ctx context.Context, in *sysin.ProfileViewInp) (res *sysin.ProfileViewModel, err error)
	FollowNoteImageSearch(ctx context.Context, in *sysin.FollowNoteListInp, file *ghttp.UploadFile) (list []*sysin.NoteModel, totalCount int, err error)
	ExecuteImportTask(ctx context.Context, id int64) (err error)
	MyMediaUpload(ctx context.Context, in *sysin.MediaUploadInp, file *ghttp.UploadFile, poster *ghttp.UploadFile, originalFile *ghttp.UploadFile) (res *sysin.MediaModel, err error)
	MyMediaList(ctx context.Context, in *sysin.MediaListInp) (list []*sysin.MediaModel, err error)
	TelegramWebhookRaw(ctx context.Context, botId int64, body []byte) (err error)
	TelegramLoginStart(ctx context.Context, in *sysin.TelegramLoginStartInp) (res *sysin.TelegramLoginModel, err error)
	TelegramLoginStatus(ctx context.Context, in *sysin.TelegramLoginStatusInp) (res *sysin.TelegramLoginModel, err error)
	TelegramLoginPassword(ctx context.Context, in *sysin.TelegramLoginPasswordInp) (res *sysin.TelegramLoginModel, err error)
	AdminInviteList(ctx context.Context, in *sysin.InviteListInp) (list []*sysin.InviteModel, totalCount int, err error)
}

var localSysPublish ISysPublish

func SysPublish() ISysPublish {
	if localSysPublish == nil {
		panic("implement not found for interface ISysPublish, forgot register?")
	}
	return localSysPublish
}

func RegisterSysPublish(i ISysPublish) {
	localSysPublish = i
}
