CREATE TABLE IF NOT EXISTS `hg_youban_two_way_bot_bot` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `tenant_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '租户ID',
  `account_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '创建账号ID',
  `tg_account_id` bigint(20) NOT NULL DEFAULT '0' COMMENT 'TG协议号ID',
  `name` varchar(128) NOT NULL DEFAULT '' COMMENT '名称',
  `bot_token` varchar(255) NOT NULL DEFAULT '' COMMENT 'Bot Token',
  `bot_user_id` varchar(64) NOT NULL DEFAULT '' COMMENT 'Bot用户ID',
  `bot_username` varchar(128) NOT NULL DEFAULT '' COMMENT 'Bot用户名',
  `supergroup_id` varchar(64) NOT NULL DEFAULT '' COMMENT '管理群ID',
  `supergroup_access_hash` varchar(128) NOT NULL DEFAULT '' COMMENT '管理群AccessHash',
  `supergroup_title` varchar(128) NOT NULL DEFAULT '' COMMENT '管理群名称',
  `invite_link` varchar(512) NOT NULL DEFAULT '' COMMENT '邀请链接',
  `setup_status` varchar(32) NOT NULL DEFAULT 'pending' COMMENT '初始化状态',
  `webhook_status` varchar(32) NOT NULL DEFAULT 'pending' COMMENT 'Webhook状态',
  `status` tinyint(1) NOT NULL DEFAULT '1' COMMENT '状态',
  `error_message` varchar(1024) NOT NULL DEFAULT '' COMMENT '错误信息',
  `last_setup_at` datetime DEFAULT NULL COMMENT '最后初始化时间',
  `last_webhook_at` datetime DEFAULT NULL COMMENT '最后Webhook时间',
  `created_at` datetime DEFAULT NULL COMMENT '创建时间',
  `updated_at` datetime DEFAULT NULL COMMENT '更新时间',
  `deleted_at` datetime DEFAULT NULL COMMENT '删除时间',
  PRIMARY KEY (`id`),
  KEY `idx_ybtwb_bot_tenant` (`tenant_id`,`status`,`id`),
  KEY `idx_ybtwb_bot_tg_account` (`tenant_id`,`tg_account_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='双向机器人';

CREATE TABLE IF NOT EXISTS `hg_youban_two_way_bot_topic` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `tenant_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '租户ID',
  `bot_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '机器人ID',
  `telegram_user_id` varchar(64) NOT NULL DEFAULT '' COMMENT 'TG用户ID',
  `telegram_username` varchar(128) NOT NULL DEFAULT '' COMMENT 'TG用户名',
  `telegram_first_name` varchar(128) NOT NULL DEFAULT '' COMMENT 'TG名',
  `telegram_last_name` varchar(128) NOT NULL DEFAULT '' COMMENT 'TG姓',
  `thread_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '话题ID',
  `title` varchar(128) NOT NULL DEFAULT '' COMMENT '话题标题',
  `closed` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否关闭',
  `last_message_at` datetime DEFAULT NULL COMMENT '最后消息时间',
  `created_at` datetime DEFAULT NULL COMMENT '创建时间',
  `updated_at` datetime DEFAULT NULL COMMENT '更新时间',
  `deleted_at` datetime DEFAULT NULL COMMENT '删除时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ybtwb_topic_user` (`tenant_id`,`bot_id`,`telegram_user_id`),
  UNIQUE KEY `uk_ybtwb_topic_thread` (`tenant_id`,`bot_id`,`thread_id`),
  KEY `idx_ybtwb_topic_last` (`tenant_id`,`bot_id`,`last_message_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='双向机器人话题';

CREATE TABLE IF NOT EXISTS `hg_youban_two_way_bot_message` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `tenant_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '租户ID',
  `bot_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '机器人ID',
  `direction` varchar(16) NOT NULL DEFAULT '' COMMENT '方向',
  `telegram_user_id` varchar(64) NOT NULL DEFAULT '' COMMENT 'TG用户ID',
  `thread_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '话题ID',
  `source_chat_id` varchar(64) NOT NULL DEFAULT '' COMMENT '源聊天ID',
  `source_message_id` int(11) NOT NULL DEFAULT '0' COMMENT '源消息ID',
  `target_chat_id` varchar(64) NOT NULL DEFAULT '' COMMENT '目标聊天ID',
  `target_message_id` int(11) NOT NULL DEFAULT '0' COMMENT '目标消息ID',
  `media_group_id` varchar(128) NOT NULL DEFAULT '' COMMENT '媒体组ID',
  `status` varchar(32) NOT NULL DEFAULT 'sent' COMMENT '状态',
  `error_message` varchar(1024) NOT NULL DEFAULT '' COMMENT '错误信息',
  `created_at` datetime DEFAULT NULL COMMENT '创建时间',
  `updated_at` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_ybtwb_msg_topic` (`tenant_id`,`bot_id`,`thread_id`,`id`),
  KEY `idx_ybtwb_msg_user` (`tenant_id`,`bot_id`,`telegram_user_id`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='双向机器人消息';
