// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/addons/youban_publish/internal/dao/internal"
)

// youbanPublishAccountFollowDao is the data access object for the table hg_youban_publish_account_follow.
// You can define custom methods on it to extend its functionality as needed.
type youbanPublishAccountFollowDao struct {
	*internal.YoubanPublishAccountFollowDao
}

var (
	// YoubanPublishAccountFollow is a globally accessible object for table hg_youban_publish_account_follow operations.
	YoubanPublishAccountFollow = youbanPublishAccountFollowDao{internal.NewYoubanPublishAccountFollowDao()}
)

// Add your custom methods and functionality below.
