// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/addons/youban_publish/internal/dao/internal"
)

// youbanPublishTenantVipDao is the data access object for the table hg_youban_publish_tenant_vip.
// You can define custom methods on it to extend its functionality as needed.
type youbanPublishTenantVipDao struct {
	*internal.YoubanPublishTenantVipDao
}

var (
	// YoubanPublishTenantVip is a globally accessible object for table hg_youban_publish_tenant_vip operations.
	YoubanPublishTenantVip = youbanPublishTenantVipDao{internal.NewYoubanPublishTenantVipDao()}
)

// Add your custom methods and functionality below.
