// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/addons/youban_publish/internal/dao/internal"
)

// youbanPublishCollectEventDao is the data access object for the table hg_youban_publish_collect_event.
// You can define custom methods on it to extend its functionality as needed.
type youbanPublishCollectEventDao struct {
	*internal.YoubanPublishCollectEventDao
}

var (
	// YoubanPublishCollectEvent is a globally accessible object for table hg_youban_publish_collect_event operations.
	YoubanPublishCollectEvent = youbanPublishCollectEventDao{internal.NewYoubanPublishCollectEventDao()}
)

// Add your custom methods and functionality below.
