// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/addons/youban_publish/internal/dao/internal"
)

// youbanPublishImportMatchCandidateDao is the data access object for the table hg_youban_publish_import_match_candidate.
// You can define custom methods on it to extend its functionality as needed.
type youbanPublishImportMatchCandidateDao struct {
	*internal.YoubanPublishImportMatchCandidateDao
}

var (
	// YoubanPublishImportMatchCandidate is a globally accessible object for table hg_youban_publish_import_match_candidate operations.
	YoubanPublishImportMatchCandidate = youbanPublishImportMatchCandidateDao{internal.NewYoubanPublishImportMatchCandidateDao()}
)

// Add your custom methods and functionality below.
