// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/addons/youban_publish/internal/dao/internal"
)

// youbanPublishCollectEventLogDao is the data access object for the table hg_youban_publish_collect_event_log.
// You can define custom methods on it to extend its functionality as needed.
type youbanPublishCollectEventLogDao struct {
	*internal.YoubanPublishCollectEventLogDao
}

var (
	// YoubanPublishCollectEventLog is a globally accessible object for table hg_youban_publish_collect_event_log operations.
	YoubanPublishCollectEventLog = youbanPublishCollectEventLogDao{internal.NewYoubanPublishCollectEventLogDao()}
)

// Add your custom methods and functionality below.
