// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/addons/youban_publish/internal/dao/internal"
)

// youbanPublishTaskDao is the data access object for the table hg_youban_publish_task.
// You can define custom methods on it to extend its functionality as needed.
type youbanPublishTaskDao struct {
	*internal.YoubanPublishTaskDao
}

var (
	// YoubanPublishTask is a globally accessible object for table hg_youban_publish_task operations.
	YoubanPublishTask = youbanPublishTaskDao{internal.NewYoubanPublishTaskDao()}
)

// Add your custom methods and functionality below.
