// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/addons/youban_publish/internal/dao/internal"
)

// youbanPublishCyclePlanDao is the data access object for the table hg_youban_publish_cycle_plan.
// You can define custom methods on it to extend its functionality as needed.
type youbanPublishCyclePlanDao struct {
	*internal.YoubanPublishCyclePlanDao
}

var (
	// YoubanPublishCyclePlan is a globally accessible object for table hg_youban_publish_cycle_plan operations.
	YoubanPublishCyclePlan = youbanPublishCyclePlanDao{internal.NewYoubanPublishCyclePlanDao()}
)

// Add your custom methods and functionality below.
