// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/addons/youban_publish/internal/dao/internal"
)

// youbanPublishMediaDao is the data access object for the table hg_youban_publish_media.
// You can define custom methods on it to extend its functionality as needed.
type youbanPublishMediaDao struct {
	*internal.YoubanPublishMediaDao
}

var (
	// YoubanPublishMedia is a globally accessible object for table hg_youban_publish_media operations.
	YoubanPublishMedia = youbanPublishMediaDao{internal.NewYoubanPublishMediaDao()}
)

// Add your custom methods and functionality below.
