// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/addons/youban_publish/internal/dao/internal"
)

// youbanPublishCollectSourceDao is the data access object for the table hg_youban_publish_collect_source.
// You can define custom methods on it to extend its functionality as needed.
type youbanPublishCollectSourceDao struct {
	*internal.YoubanPublishCollectSourceDao
}

var (
	// YoubanPublishCollectSource is a globally accessible object for table hg_youban_publish_collect_source operations.
	YoubanPublishCollectSource = youbanPublishCollectSourceDao{internal.NewYoubanPublishCollectSourceDao()}
)

// Add your custom methods and functionality below.
