// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/addons/youban_publish/internal/dao/internal"
)

// youbanPublishCollectContentDao is the data access object for the table hg_youban_publish_collect_content.
// You can define custom methods on it to extend its functionality as needed.
type youbanPublishCollectContentDao struct {
	*internal.YoubanPublishCollectContentDao
}

var (
	// YoubanPublishCollectContent is a globally accessible object for table hg_youban_publish_collect_content operations.
	YoubanPublishCollectContent = youbanPublishCollectContentDao{internal.NewYoubanPublishCollectContentDao()}
)

// Add your custom methods and functionality below.
