// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/addons/youban_publish/internal/dao/internal"
)

// youbanPublishImportMatchRunDao is the data access object for the table hg_youban_publish_import_match_run.
// You can define custom methods on it to extend its functionality as needed.
type youbanPublishImportMatchRunDao struct {
	*internal.YoubanPublishImportMatchRunDao
}

var (
	// YoubanPublishImportMatchRun is a globally accessible object for table hg_youban_publish_import_match_run operations.
	YoubanPublishImportMatchRun = youbanPublishImportMatchRunDao{internal.NewYoubanPublishImportMatchRunDao()}
)

// Add your custom methods and functionality below.
