// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/addons/youban_publish/internal/dao/internal"
)

// youbanPublishTgQueueStatDao is the data access object for the table hg_youban_publish_tg_queue_stat.
// You can define custom methods on it to extend its functionality as needed.
type youbanPublishTgQueueStatDao struct {
	*internal.YoubanPublishTgQueueStatDao
}

var (
	// YoubanPublishTgQueueStat is a globally accessible object for table hg_youban_publish_tg_queue_stat operations.
	YoubanPublishTgQueueStat = youbanPublishTgQueueStatDao{internal.NewYoubanPublishTgQueueStatDao()}
)

// Add your custom methods and functionality below.
