// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/addons/youban_publish/internal/dao/internal"
)

// youbanPublishNoteIndexDao is the data access object for the table hg_youban_publish_note_index.
// You can define custom methods on it to extend its functionality as needed.
type youbanPublishNoteIndexDao struct {
	*internal.YoubanPublishNoteIndexDao
}

var (
	// YoubanPublishNoteIndex is a globally accessible object for table hg_youban_publish_note_index operations.
	YoubanPublishNoteIndex = youbanPublishNoteIndexDao{internal.NewYoubanPublishNoteIndexDao()}
)

// Add your custom methods and functionality below.
