// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/addons/youban_publish/internal/dao/internal"
)

// youbanPublishTagDao is the data access object for the table hg_youban_publish_tag.
// You can define custom methods on it to extend its functionality as needed.
type youbanPublishTagDao struct {
	*internal.YoubanPublishTagDao
}

var (
	// YoubanPublishTag is a globally accessible object for table hg_youban_publish_tag operations.
	YoubanPublishTag = youbanPublishTagDao{internal.NewYoubanPublishTagDao()}
)

// Add your custom methods and functionality below.
