// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/addons/youban_publish/internal/dao/internal"
)

// youbanPublishNoticeDao is the data access object for the table hg_youban_publish_notice.
// You can define custom methods on it to extend its functionality as needed.
type youbanPublishNoticeDao struct {
	*internal.YoubanPublishNoticeDao
}

var (
	// YoubanPublishNotice is a globally accessible object for table hg_youban_publish_notice operations.
	YoubanPublishNotice = youbanPublishNoticeDao{internal.NewYoubanPublishNoticeDao()}
)

// Add your custom methods and functionality below.
