// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/addons/youban_publish/internal/dao/internal"
)

// youbanPublishCollectHistoryTaskDao is the data access object for the table hg_youban_publish_collect_history_task.
// You can define custom methods on it to extend its functionality as needed.
type youbanPublishCollectHistoryTaskDao struct {
	*internal.YoubanPublishCollectHistoryTaskDao
}

var (
	// YoubanPublishCollectHistoryTask is a globally accessible object for table hg_youban_publish_collect_history_task operations.
	YoubanPublishCollectHistoryTask = youbanPublishCollectHistoryTaskDao{internal.NewYoubanPublishCollectHistoryTaskDao()}
)

// Add your custom methods and functionality below.
