// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/addons/youban_publish/internal/dao/internal"
)

// youbanPublishCollectRuleDao is the data access object for the table hg_youban_publish_collect_rule.
// You can define custom methods on it to extend its functionality as needed.
type youbanPublishCollectRuleDao struct {
	*internal.YoubanPublishCollectRuleDao
}

var (
	// YoubanPublishCollectRule is a globally accessible object for table hg_youban_publish_collect_rule operations.
	YoubanPublishCollectRule = youbanPublishCollectRuleDao{internal.NewYoubanPublishCollectRuleDao()}
)

// Add your custom methods and functionality below.
