// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/addons/youban_publish/internal/dao/internal"
)

// youbanPublishAccountDao is the data access object for the table hg_youban_publish_account.
// You can define custom methods on it to extend its functionality as needed.
type youbanPublishAccountDao struct {
	*internal.YoubanPublishAccountDao
}

var (
	// YoubanPublishAccount is a globally accessible object for table hg_youban_publish_account operations.
	YoubanPublishAccount = youbanPublishAccountDao{internal.NewYoubanPublishAccountDao()}
)

// Add your custom methods and functionality below.
