// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/addons/youban_publish/internal/dao/internal"
)

// youbanPublishTenantVipLogDao is the data access object for the table hg_youban_publish_tenant_vip_log.
// You can define custom methods on it to extend its functionality as needed.
type youbanPublishTenantVipLogDao struct {
	*internal.YoubanPublishTenantVipLogDao
}

var (
	// YoubanPublishTenantVipLog is a globally accessible object for table hg_youban_publish_tenant_vip_log operations.
	YoubanPublishTenantVipLog = youbanPublishTenantVipLogDao{internal.NewYoubanPublishTenantVipLogDao()}
)

// Add your custom methods and functionality below.
