// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/addons/youban_publish/internal/dao/internal"
)

// youbanPublishCycleRunDao is the data access object for the table hg_youban_publish_cycle_run.
// You can define custom methods on it to extend its functionality as needed.
type youbanPublishCycleRunDao struct {
	*internal.YoubanPublishCycleRunDao
}

var (
	// YoubanPublishCycleRun is a globally accessible object for table hg_youban_publish_cycle_run operations.
	YoubanPublishCycleRun = youbanPublishCycleRunDao{internal.NewYoubanPublishCycleRunDao()}
)

// Add your custom methods and functionality below.
