// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/addons/youban_publish/internal/dao/internal"
)

// youbanPublishTenantDao is the data access object for the table hg_youban_publish_tenant.
// You can define custom methods on it to extend its functionality as needed.
type youbanPublishTenantDao struct {
	*internal.YoubanPublishTenantDao
}

var (
	// YoubanPublishTenant is a globally accessible object for table hg_youban_publish_tenant operations.
	YoubanPublishTenant = youbanPublishTenantDao{internal.NewYoubanPublishTenantDao()}
)

// Add your custom methods and functionality below.
