// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/addons/youban_publish/internal/dao/internal"
)

// youbanPublishTgChannelStatDao is the data access object for the table hg_youban_publish_tg_channel_stat.
// You can define custom methods on it to extend its functionality as needed.
type youbanPublishTgChannelStatDao struct {
	*internal.YoubanPublishTgChannelStatDao
}

var (
	// YoubanPublishTgChannelStat is a globally accessible object for table hg_youban_publish_tg_channel_stat operations.
	YoubanPublishTgChannelStat = youbanPublishTgChannelStatDao{internal.NewYoubanPublishTgChannelStatDao()}
)

// Add your custom methods and functionality below.
