// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/addons/youban_publish/internal/dao/internal"
)

// youbanPublishCollectSourceRuleDao is the data access object for the table hg_youban_publish_collect_source_rule.
// You can define custom methods on it to extend its functionality as needed.
type youbanPublishCollectSourceRuleDao struct {
	*internal.YoubanPublishCollectSourceRuleDao
}

var (
	// YoubanPublishCollectSourceRule is a globally accessible object for table hg_youban_publish_collect_source_rule operations.
	YoubanPublishCollectSourceRule = youbanPublishCollectSourceRuleDao{internal.NewYoubanPublishCollectSourceRuleDao()}
)

// Add your custom methods and functionality below.
