// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/addons/youban_publish/internal/dao/internal"
)

// youbanPublishCollectContentMediaDao is the data access object for the table hg_youban_publish_collect_content_media.
// You can define custom methods on it to extend its functionality as needed.
type youbanPublishCollectContentMediaDao struct {
	*internal.YoubanPublishCollectContentMediaDao
}

var (
	// YoubanPublishCollectContentMedia is a globally accessible object for table hg_youban_publish_collect_content_media operations.
	YoubanPublishCollectContentMedia = youbanPublishCollectContentMediaDao{internal.NewYoubanPublishCollectContentMediaDao()}
)

// Add your custom methods and functionality below.
