// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/addons/youban_publish/internal/dao/internal"
)

// youbanPublishCycleRunLogDao is the data access object for the table hg_youban_publish_cycle_run_log.
// You can define custom methods on it to extend its functionality as needed.
type youbanPublishCycleRunLogDao struct {
	*internal.YoubanPublishCycleRunLogDao
}

var (
	// YoubanPublishCycleRunLog is a globally accessible object for table hg_youban_publish_cycle_run_log operations.
	YoubanPublishCycleRunLog = youbanPublishCycleRunLogDao{internal.NewYoubanPublishCycleRunLogDao()}
)

// Add your custom methods and functionality below.
