// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/addons/youban_publish/internal/dao/internal"
)

// youbanPublishChannelDao is the data access object for the table hg_youban_publish_channel.
// You can define custom methods on it to extend its functionality as needed.
type youbanPublishChannelDao struct {
	*internal.YoubanPublishChannelDao
}

var (
	// YoubanPublishChannel is a globally accessible object for table hg_youban_publish_channel operations.
	YoubanPublishChannel = youbanPublishChannelDao{internal.NewYoubanPublishChannelDao()}
)

// Add your custom methods and functionality below.
