// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/addons/youban_publish/internal/dao/internal"
)

// youbanPublishTgChannelDao is the data access object for the table hg_youban_publish_tg_channel.
// You can define custom methods on it to extend its functionality as needed.
type youbanPublishTgChannelDao struct {
	*internal.YoubanPublishTgChannelDao
}

var (
	// YoubanPublishTgChannel is a globally accessible object for table hg_youban_publish_tg_channel operations.
	YoubanPublishTgChannel = youbanPublishTgChannelDao{internal.NewYoubanPublishTgChannelDao()}
)

// Add your custom methods and functionality below.
