// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/addons/youban_publish/internal/dao/internal"
)

// youbanPublishTgMessageDao is the data access object for the table hg_youban_publish_tg_message.
// You can define custom methods on it to extend its functionality as needed.
type youbanPublishTgMessageDao struct {
	*internal.YoubanPublishTgMessageDao
}

var (
	// YoubanPublishTgMessage is a globally accessible object for table hg_youban_publish_tg_message operations.
	YoubanPublishTgMessage = youbanPublishTgMessageDao{internal.NewYoubanPublishTgMessageDao()}
)

// Add your custom methods and functionality below.
