// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/addons/youban_publish/internal/dao/internal"
)

// youbanPublishNoticeReadDao is the data access object for the table hg_youban_publish_notice_read.
// You can define custom methods on it to extend its functionality as needed.
type youbanPublishNoticeReadDao struct {
	*internal.YoubanPublishNoticeReadDao
}

var (
	// YoubanPublishNoticeRead is a globally accessible object for table hg_youban_publish_notice_read operations.
	YoubanPublishNoticeRead = youbanPublishNoticeReadDao{internal.NewYoubanPublishNoticeReadDao()}
)

// Add your custom methods and functionality below.
