// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/addons/youban_publish/internal/dao/internal"
)

// youbanPublishTgLoginDao is the data access object for the table hg_youban_publish_tg_login.
// You can define custom methods on it to extend its functionality as needed.
type youbanPublishTgLoginDao struct {
	*internal.YoubanPublishTgLoginDao
}

var (
	// YoubanPublishTgLogin is a globally accessible object for table hg_youban_publish_tg_login operations.
	YoubanPublishTgLogin = youbanPublishTgLoginDao{internal.NewYoubanPublishTgLoginDao()}
)

// Add your custom methods and functionality below.
