// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/addons/youban_publish/internal/dao/internal"
)

// youbanPublishTgJobLogDao is the data access object for the table hg_youban_publish_tg_job_log.
// You can define custom methods on it to extend its functionality as needed.
type youbanPublishTgJobLogDao struct {
	*internal.YoubanPublishTgJobLogDao
}

var (
	// YoubanPublishTgJobLog is a globally accessible object for table hg_youban_publish_tg_job_log operations.
	YoubanPublishTgJobLog = youbanPublishTgJobLogDao{internal.NewYoubanPublishTgJobLogDao()}
)

// Add your custom methods and functionality below.
