// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/addons/youban_publish/internal/dao/internal"
)

// youbanPublishMerchantDao is the data access object for the table hg_youban_publish_merchant.
// You can define custom methods on it to extend its functionality as needed.
type youbanPublishMerchantDao struct {
	*internal.YoubanPublishMerchantDao
}

var (
	// YoubanPublishMerchant is a globally accessible object for table hg_youban_publish_merchant operations.
	YoubanPublishMerchant = youbanPublishMerchantDao{internal.NewYoubanPublishMerchantDao()}
)

// Add your custom methods and functionality below.
