// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/addons/youban_publish/internal/dao/internal"
)

// youbanPublishImportMatchItemDao is the data access object for the table hg_youban_publish_import_match_item.
// You can define custom methods on it to extend its functionality as needed.
type youbanPublishImportMatchItemDao struct {
	*internal.YoubanPublishImportMatchItemDao
}

var (
	// YoubanPublishImportMatchItem is a globally accessible object for table hg_youban_publish_import_match_item operations.
	YoubanPublishImportMatchItem = youbanPublishImportMatchItemDao{internal.NewYoubanPublishImportMatchItemDao()}
)

// Add your custom methods and functionality below.
