// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/addons/youban_publish/internal/dao/internal"
)

// youbanPublishCollectEventMediaDao is the data access object for the table hg_youban_publish_collect_event_media.
// You can define custom methods on it to extend its functionality as needed.
type youbanPublishCollectEventMediaDao struct {
	*internal.YoubanPublishCollectEventMediaDao
}

var (
	// YoubanPublishCollectEventMedia is a globally accessible object for table hg_youban_publish_collect_event_media operations.
	YoubanPublishCollectEventMedia = youbanPublishCollectEventMediaDao{internal.NewYoubanPublishCollectEventMediaDao()}
)

// Add your custom methods and functionality below.
