// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/addons/youban_publish/internal/dao/internal"
)

// youbanPublishTenantAutoDeleteConfigDao is the data access object for the table hg_youban_publish_tenant_auto_delete_config.
// You can define custom methods on it to extend its functionality as needed.
type youbanPublishTenantAutoDeleteConfigDao struct {
	*internal.YoubanPublishTenantAutoDeleteConfigDao
}

var (
	// YoubanPublishTenantAutoDeleteConfig is a globally accessible object for table hg_youban_publish_tenant_auto_delete_config operations.
	YoubanPublishTenantAutoDeleteConfig = youbanPublishTenantAutoDeleteConfigDao{internal.NewYoubanPublishTenantAutoDeleteConfigDao()}
)

// Add your custom methods and functionality below.
