// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/addons/youban_publish/internal/dao/internal"
)

// youbanPublishCollectDispatchDao is the data access object for the table hg_youban_publish_collect_dispatch.
// You can define custom methods on it to extend its functionality as needed.
type youbanPublishCollectDispatchDao struct {
	*internal.YoubanPublishCollectDispatchDao
}

var (
	// YoubanPublishCollectDispatch is a globally accessible object for table hg_youban_publish_collect_dispatch operations.
	YoubanPublishCollectDispatch = youbanPublishCollectDispatchDao{internal.NewYoubanPublishCollectDispatchDao()}
)

// Add your custom methods and functionality below.
