// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/addons/youban_publish/internal/dao/internal"
)

// youbanPublishCollectHistoryLogDao is the data access object for the table hg_youban_publish_collect_history_log.
// You can define custom methods on it to extend its functionality as needed.
type youbanPublishCollectHistoryLogDao struct {
	*internal.YoubanPublishCollectHistoryLogDao
}

var (
	// YoubanPublishCollectHistoryLog is a globally accessible object for table hg_youban_publish_collect_history_log operations.
	YoubanPublishCollectHistoryLog = youbanPublishCollectHistoryLogDao{internal.NewYoubanPublishCollectHistoryLogDao()}
)

// Add your custom methods and functionality below.
