// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/addons/youban_publish/internal/dao/internal"
)

// youbanPublishTgJobDao is the data access object for the table hg_youban_publish_tg_job.
// You can define custom methods on it to extend its functionality as needed.
type youbanPublishTgJobDao struct {
	*internal.YoubanPublishTgJobDao
}

var (
	// YoubanPublishTgJob is a globally accessible object for table hg_youban_publish_tg_job operations.
	YoubanPublishTgJob = youbanPublishTgJobDao{internal.NewYoubanPublishTgJobDao()}
)

// Add your custom methods and functionality below.
