// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/addons/youban_publish/internal/dao/internal"
)

// youbanPublishCollectReviewDao is the data access object for the table hg_youban_publish_collect_review.
// You can define custom methods on it to extend its functionality as needed.
type youbanPublishCollectReviewDao struct {
	*internal.YoubanPublishCollectReviewDao
}

var (
	// YoubanPublishCollectReview is a globally accessible object for table hg_youban_publish_collect_review operations.
	YoubanPublishCollectReview = youbanPublishCollectReviewDao{internal.NewYoubanPublishCollectReviewDao()}
)

// Add your custom methods and functionality below.
