// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/addons/youban_publish/internal/dao/internal"
)

// youbanPublishMaterialImportTaskDao is the data access object for the table hg_youban_publish_material_import_task.
// You can define custom methods on it to extend its functionality as needed.
type youbanPublishMaterialImportTaskDao struct {
	*internal.YoubanPublishMaterialImportTaskDao
}

var (
	// YoubanPublishMaterialImportTask is a globally accessible object for table hg_youban_publish_material_import_task operations.
	YoubanPublishMaterialImportTask = youbanPublishMaterialImportTaskDao{internal.NewYoubanPublishMaterialImportTaskDao()}
)

// Add your custom methods and functionality below.
