// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/addons/youban_publish/internal/dao/internal"
)

// youbanPublishBotDao is the data access object for the table hg_youban_publish_bot.
// You can define custom methods on it to extend its functionality as needed.
type youbanPublishBotDao struct {
	*internal.YoubanPublishBotDao
}

var (
	// YoubanPublishBot is a globally accessible object for table hg_youban_publish_bot operations.
	YoubanPublishBot = youbanPublishBotDao{internal.NewYoubanPublishBotDao()}
)

// Add your custom methods and functionality below.
