// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/addons/youban_publish/internal/dao/internal"
)

// youbanPublishTgBotStatDao is the data access object for the table hg_youban_publish_tg_bot_stat.
// You can define custom methods on it to extend its functionality as needed.
type youbanPublishTgBotStatDao struct {
	*internal.YoubanPublishTgBotStatDao
}

var (
	// YoubanPublishTgBotStat is a globally accessible object for table hg_youban_publish_tg_bot_stat operations.
	YoubanPublishTgBotStat = youbanPublishTgBotStatDao{internal.NewYoubanPublishTgBotStatDao()}
)

// Add your custom methods and functionality below.
