// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/addons/youban_publish/internal/dao/internal"
)

// youbanPublishMessagePushPlanDao is the data access object for the table hg_youban_publish_message_push_plan.
// You can define custom methods on it to extend its functionality as needed.
type youbanPublishMessagePushPlanDao struct {
	*internal.YoubanPublishMessagePushPlanDao
}

var (
	// YoubanPublishMessagePushPlan is a globally accessible object for table hg_youban_publish_message_push_plan operations.
	YoubanPublishMessagePushPlan = youbanPublishMessagePushPlanDao{internal.NewYoubanPublishMessagePushPlanDao()}
)

// Add your custom methods and functionality below.
