// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/addons/youban_publish/internal/dao/internal"
)

// youbanPublishImportTaskDao is the data access object for the table hg_youban_publish_import_task.
// You can define custom methods on it to extend its functionality as needed.
type youbanPublishImportTaskDao struct {
	*internal.YoubanPublishImportTaskDao
}

var (
	// YoubanPublishImportTask is a globally accessible object for table hg_youban_publish_import_task operations.
	YoubanPublishImportTask = youbanPublishImportTaskDao{internal.NewYoubanPublishImportTaskDao()}
)

// Add your custom methods and functionality below.
