
CREATE TABLE IF NOT EXISTS hg_youban_feiniu_sync_config (
  id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  name varchar(128) NOT NULL DEFAULT '',
  db_type varchar(32) NOT NULL DEFAULT 'mysql',
  db_host varchar(255) NOT NULL DEFAULT '',
  db_port int(11) NOT NULL DEFAULT '3306',
  db_name varchar(128) NOT NULL DEFAULT '',
  db_user varchar(128) NOT NULL DEFAULT '',
  db_password varchar(1024) NOT NULL DEFAULT '',
  target_tenant_id bigint(20) NOT NULL DEFAULT '0',
  target_parent_account_id bigint(20) NOT NULL DEFAULT '0',
  auto_create_account tinyint(1) NOT NULL DEFAULT '1',
  sync_media tinyint(1) NOT NULL DEFAULT '1',
  sync_verify_media tinyint(1) NOT NULL DEFAULT '1',
  auto_sync_enabled tinyint(1) NOT NULL DEFAULT '1',
  sync_interval_minutes int(11) NOT NULL DEFAULT '10',
  batch_size int(11) NOT NULL DEFAULT '100',
  last_source_note_id bigint(20) NOT NULL DEFAULT '0',
  last_source_update_time datetime DEFAULT NULL,
  last_source_update_note_id bigint(20) NOT NULL DEFAULT '0',
  backfill_source_note_id bigint(20) NOT NULL DEFAULT '0',
  backfill_target_note_id bigint(20) NOT NULL DEFAULT '0',
  backfill_completed_at datetime DEFAULT NULL,
  status tinyint(1) NOT NULL DEFAULT '1',
  last_run_at datetime DEFAULT NULL,
  last_success_at datetime DEFAULT NULL,
  last_error text,
  created_at datetime DEFAULT NULL,
  updated_at datetime DEFAULT NULL,
  deleted_at datetime DEFAULT NULL,
  PRIMARY KEY (id),
  KEY idx_yfs_config_status (status,id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='FeiNiu同步配置';
CREATE TABLE IF NOT EXISTS hg_youban_feiniu_sync_channel_map (
  id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  config_id bigint(20) NOT NULL DEFAULT '0',
  feiniu_channel_id bigint(20) NOT NULL DEFAULT '0',
  feiniu_tg_chat_id bigint(20) NOT NULL DEFAULT '0',
  feiniu_channel_title varchar(255) NOT NULL DEFAULT '',
  feiniu_username varchar(255) NOT NULL DEFAULT '',
  youban_tenant_id bigint(20) NOT NULL DEFAULT '0',
  youban_account_id bigint(20) NOT NULL DEFAULT '0',
  youban_account_username varchar(128) NOT NULL DEFAULT '',
  last_source_update_time datetime DEFAULT NULL,
  last_source_note_id bigint(20) NOT NULL DEFAULT '0',
  sync_status varchar(32) NOT NULL DEFAULT 'pending',
  error_message text,
  created_at datetime DEFAULT NULL,
  updated_at datetime DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_yfs_channel (config_id,feiniu_channel_id),
  KEY idx_yfs_channel_chat (config_id,feiniu_tg_chat_id),
  KEY idx_yfs_channel_account (youban_tenant_id,youban_account_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='FeiNiu频道映射';
ALTER TABLE hg_youban_feiniu_sync_channel_map ADD INDEX idx_yfs_channel_chat (config_id,feiniu_tg_chat_id);
CREATE TABLE IF NOT EXISTS hg_youban_feiniu_sync_profile_map (
  id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  config_id bigint(20) NOT NULL DEFAULT '0',
  feiniu_note_id bigint(20) NOT NULL DEFAULT '0',
  feiniu_note_uuid varchar(64) NOT NULL DEFAULT '',
  feiniu_note_code varchar(32) NOT NULL DEFAULT '',
  feiniu_source_key varchar(255) NOT NULL DEFAULT '',
  feiniu_channel_id bigint(20) NOT NULL DEFAULT '0',
  feiniu_tg_chat_id bigint(20) NOT NULL DEFAULT '0',
  youban_profile_id bigint(20) NOT NULL DEFAULT '0',
  youban_account_id bigint(20) NOT NULL DEFAULT '0',
  source_updated_at datetime DEFAULT NULL,
  content_hash varchar(64) NOT NULL DEFAULT '',
  dedupe_key varchar(255) NOT NULL DEFAULT '',
  duplicate_profile_id bigint(20) NOT NULL DEFAULT '0',
  sync_status varchar(32) NOT NULL DEFAULT 'pending',
  error_message text,
  created_at datetime DEFAULT NULL,
  updated_at datetime DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_yfs_profile (config_id,feiniu_note_id),
  KEY idx_yfs_profile_cursor (config_id,source_updated_at,feiniu_note_id),
  KEY idx_yfs_profile_status (config_id,sync_status,id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='FeiNiu资料映射';
CREATE TABLE IF NOT EXISTS hg_youban_feiniu_sync_run (
  id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  config_id bigint(20) NOT NULL DEFAULT '0',
  run_type varchar(32) NOT NULL DEFAULT 'manual',
  status varchar(32) NOT NULL DEFAULT 'running',
  total_count int(11) NOT NULL DEFAULT '0',
  created_count int(11) NOT NULL DEFAULT '0',
  updated_count int(11) NOT NULL DEFAULT '0',
  skipped_count int(11) NOT NULL DEFAULT '0',
  failed_count int(11) NOT NULL DEFAULT '0',
  started_at datetime DEFAULT NULL,
  finished_at datetime DEFAULT NULL,
  error_message text,
  runtime_log longtext,
  created_at datetime DEFAULT NULL,
  PRIMARY KEY (id),
  KEY idx_yfs_run_config (config_id,id),
  KEY idx_yfs_run_status (status,id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='FeiNiu同步运行记录';

CREATE TABLE IF NOT EXISTS hg_youban_feiniu_sync_daily_stat (
  id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  stat_date date NOT NULL,
  config_id bigint(20) NOT NULL DEFAULT '0',
  run_count int(11) NOT NULL DEFAULT '0',
  total_count int(11) NOT NULL DEFAULT '0',
  success_count int(11) NOT NULL DEFAULT '0',
  created_count int(11) NOT NULL DEFAULT '0',
  updated_count int(11) NOT NULL DEFAULT '0',
  skipped_count int(11) NOT NULL DEFAULT '0',
  failed_count int(11) NOT NULL DEFAULT '0',
  channel_count int(11) NOT NULL DEFAULT '0',
  profile_count int(11) NOT NULL DEFAULT '0',
  avg_duration_ms bigint(20) NOT NULL DEFAULT '0',
  last_run_id bigint(20) NOT NULL DEFAULT '0',
  last_run_at datetime DEFAULT NULL,
  created_at datetime DEFAULT NULL,
  updated_at datetime DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_yfs_daily (config_id,stat_date),
  KEY idx_yfs_daily_date (stat_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='FeiNiu同步每日统计';
CREATE TABLE IF NOT EXISTS hg_youban_feiniu_sync_channel_daily_stat (
  id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  stat_date date NOT NULL,
  config_id bigint(20) NOT NULL DEFAULT '0',
  feiniu_channel_id bigint(20) NOT NULL DEFAULT '0',
  feiniu_tg_chat_id bigint(20) NOT NULL DEFAULT '0',
  feiniu_channel_title varchar(255) NOT NULL DEFAULT '',
  youban_account_id bigint(20) NOT NULL DEFAULT '0',
  youban_account_username varchar(128) NOT NULL DEFAULT '',
  total_count int(11) NOT NULL DEFAULT '0',
  created_count int(11) NOT NULL DEFAULT '0',
  updated_count int(11) NOT NULL DEFAULT '0',
  skipped_count int(11) NOT NULL DEFAULT '0',
  failed_count int(11) NOT NULL DEFAULT '0',
  last_note_id bigint(20) NOT NULL DEFAULT '0',
  last_source_update_time datetime DEFAULT NULL,
  created_at datetime DEFAULT NULL,
  updated_at datetime DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_yfs_channel_daily (config_id,stat_date,feiniu_channel_id),
  KEY idx_yfs_channel_daily_rank (config_id,stat_date,total_count)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='FeiNiu同步频道每日统计';
CREATE TABLE IF NOT EXISTS hg_youban_feiniu_sync_run_item (
  id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  run_id bigint(20) NOT NULL DEFAULT '0',
  config_id bigint(20) NOT NULL DEFAULT '0',
  feiniu_note_id bigint(20) NOT NULL DEFAULT '0',
  feiniu_note_code varchar(32) NOT NULL DEFAULT '',
  feiniu_channel_id bigint(20) NOT NULL DEFAULT '0',
  feiniu_channel_title varchar(255) NOT NULL DEFAULT '',
  youban_profile_id bigint(20) NOT NULL DEFAULT '0',
  action varchar(32) NOT NULL DEFAULT '',
  status varchar(32) NOT NULL DEFAULT '',
  error_message text,
  source_updated_at datetime DEFAULT NULL,
  duration_ms bigint(20) NOT NULL DEFAULT '0',
  created_at datetime DEFAULT NULL,
  PRIMARY KEY (id),
  KEY idx_yfs_run_item_run (run_id,id),
  KEY idx_yfs_run_item_config (config_id,created_at),
  KEY idx_yfs_run_item_status (config_id,status,created_at),
  KEY idx_yfs_run_item_channel (config_id,feiniu_channel_id,created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='FeiNiu同步运行明细';
