// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/addons/youban_two_way_bot/internal/dao/internal"
)

// youbanTwoWayBotCooperationApplicationDao is the data access object for the table hg_youban_two_way_bot_cooperation_application.
// You can define custom methods on it to extend its functionality as needed.
type youbanTwoWayBotCooperationApplicationDao struct {
	*internal.YoubanTwoWayBotCooperationApplicationDao
}

var (
	// YoubanTwoWayBotCooperationApplication is a globally accessible object for table hg_youban_two_way_bot_cooperation_application operations.
	YoubanTwoWayBotCooperationApplication = youbanTwoWayBotCooperationApplicationDao{internal.NewYoubanTwoWayBotCooperationApplicationDao()}
)

// Add your custom methods and functionality below.
