// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/addons/youban_two_way_bot/internal/dao/internal"
)

// youbanTwoWayBotCooperationBlacklistDao is the data access object for the table hg_youban_two_way_bot_cooperation_blacklist.
// You can define custom methods on it to extend its functionality as needed.
type youbanTwoWayBotCooperationBlacklistDao struct {
	*internal.YoubanTwoWayBotCooperationBlacklistDao
}

var (
	// YoubanTwoWayBotCooperationBlacklist is a globally accessible object for table hg_youban_two_way_bot_cooperation_blacklist operations.
	YoubanTwoWayBotCooperationBlacklist = youbanTwoWayBotCooperationBlacklistDao{internal.NewYoubanTwoWayBotCooperationBlacklistDao()}
)

// Add your custom methods and functionality below.
