// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/addons/youban_two_way_bot/internal/dao/internal"
)

// youbanTwoWayBotCooperationConfigDao is the data access object for the table hg_youban_two_way_bot_cooperation_config.
// You can define custom methods on it to extend its functionality as needed.
type youbanTwoWayBotCooperationConfigDao struct {
	*internal.YoubanTwoWayBotCooperationConfigDao
}

var (
	// YoubanTwoWayBotCooperationConfig is a globally accessible object for table hg_youban_two_way_bot_cooperation_config operations.
	YoubanTwoWayBotCooperationConfig = youbanTwoWayBotCooperationConfigDao{internal.NewYoubanTwoWayBotCooperationConfigDao()}
)

// Add your custom methods and functionality below.
