// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/addons/youban_two_way_bot/internal/dao/internal"
)

// youbanTwoWayBotCooperationApplicationChannelDao is the data access object for the table hg_youban_two_way_bot_cooperation_application_channel.
// You can define custom methods on it to extend its functionality as needed.
type youbanTwoWayBotCooperationApplicationChannelDao struct {
	*internal.YoubanTwoWayBotCooperationApplicationChannelDao
}

var (
	// YoubanTwoWayBotCooperationApplicationChannel is a globally accessible object for table hg_youban_two_way_bot_cooperation_application_channel operations.
	YoubanTwoWayBotCooperationApplicationChannel = youbanTwoWayBotCooperationApplicationChannelDao{internal.NewYoubanTwoWayBotCooperationApplicationChannelDao()}
)

// Add your custom methods and functionality below.
