// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/addons/youban_two_way_bot/internal/dao/internal"
)

// youbanTwoWayBotMessageDao is the data access object for the table hg_youban_two_way_bot_message.
// You can define custom methods on it to extend its functionality as needed.
type youbanTwoWayBotMessageDao struct {
	*internal.YoubanTwoWayBotMessageDao
}

var (
	// YoubanTwoWayBotMessage is a globally accessible object for table hg_youban_two_way_bot_message operations.
	YoubanTwoWayBotMessage = youbanTwoWayBotMessageDao{internal.NewYoubanTwoWayBotMessageDao()}
)

// Add your custom methods and functionality below.
