// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/addons/youban_two_way_bot/internal/dao/internal"
)

// youbanTwoWayBotBotDao is the data access object for the table hg_youban_two_way_bot_bot.
// You can define custom methods on it to extend its functionality as needed.
type youbanTwoWayBotBotDao struct {
	*internal.YoubanTwoWayBotBotDao
}

var (
	// YoubanTwoWayBotBot is a globally accessible object for table hg_youban_two_way_bot_bot operations.
	YoubanTwoWayBotBot = youbanTwoWayBotBotDao{internal.NewYoubanTwoWayBotBotDao()}
)

// Add your custom methods and functionality below.
