// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/addons/telegram_collector/internal/dao/internal"
)

// tgCollectorMediaDao is the data access object for the table hg_tg_collector_media.
// You can define custom methods on it to extend its functionality as needed.
type tgCollectorMediaDao struct {
	*internal.TgCollectorMediaDao
}

var (
	// TgCollectorMedia is a globally accessible object for table hg_tg_collector_media operations.
	TgCollectorMedia = tgCollectorMediaDao{internal.NewTgCollectorMediaDao()}
)

// Add your custom methods and functionality below.
