// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/addons/telegram_collector/internal/dao/internal"
)

// tgCollectorDeliveryDao is the data access object for the table hg_tg_collector_delivery.
// You can define custom methods on it to extend its functionality as needed.
type tgCollectorDeliveryDao struct {
	*internal.TgCollectorDeliveryDao
}

var (
	// TgCollectorDelivery is a globally accessible object for table hg_tg_collector_delivery operations.
	TgCollectorDelivery = tgCollectorDeliveryDao{internal.NewTgCollectorDeliveryDao()}
)

// Add your custom methods and functionality below.
