// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/addons/telegram_collector/internal/dao/internal"
)

// tgCollectorEventDao is the data access object for the table hg_tg_collector_event.
// You can define custom methods on it to extend its functionality as needed.
type tgCollectorEventDao struct {
	*internal.TgCollectorEventDao
}

var (
	// TgCollectorEvent is a globally accessible object for table hg_tg_collector_event operations.
	TgCollectorEvent = tgCollectorEventDao{internal.NewTgCollectorEventDao()}
)

// Add your custom methods and functionality below.
