// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/addons/telegram_collector/internal/dao/internal"
)

// tgCollectorAccountTaskDao is the data access object for the table hg_tg_collector_account_task.
// You can define custom methods on it to extend its functionality as needed.
type tgCollectorAccountTaskDao struct {
	*internal.TgCollectorAccountTaskDao
}

var (
	// TgCollectorAccountTask is a globally accessible object for table hg_tg_collector_account_task operations.
	TgCollectorAccountTask = tgCollectorAccountTaskDao{internal.NewTgCollectorAccountTaskDao()}
)

// Add your custom methods and functionality below.
