// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/addons/telegram_collector/internal/dao/internal"
)

// tgCollectorSourceDao is the data access object for the table hg_tg_collector_source.
// You can define custom methods on it to extend its functionality as needed.
type tgCollectorSourceDao struct {
	*internal.TgCollectorSourceDao
}

var (
	// TgCollectorSource is a globally accessible object for table hg_tg_collector_source operations.
	TgCollectorSource = tgCollectorSourceDao{internal.NewTgCollectorSourceDao()}
)

// Add your custom methods and functionality below.
