// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// contentSourceMapDao is the data access object for the table hg_content_source_map.
// You can define custom methods on it to extend its functionality as needed.
type contentSourceMapDao struct {
	*internal.ContentSourceMapDao
}

var (
	// ContentSourceMap is a globally accessible object for table hg_content_source_map operations.
	ContentSourceMap = contentSourceMapDao{internal.NewContentSourceMapDao()}
)

// Add your custom methods and functionality below.
