// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// contentMediaDao is the data access object for the table hg_content_media.
// You can define custom methods on it to extend its functionality as needed.
type contentMediaDao struct {
	*internal.ContentMediaDao
}

var (
	// ContentMedia is a globally accessible object for table hg_content_media operations.
	ContentMedia = contentMediaDao{internal.NewContentMediaDao()}
)

// Add your custom methods and functionality below.
