// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// contentChannelDao is the data access object for the table hg_content_channel.
// You can define custom methods on it to extend its functionality as needed.
type contentChannelDao struct {
	*internal.ContentChannelDao
}

var (
	// ContentChannel is a globally accessible object for table hg_content_channel operations.
	ContentChannel = contentChannelDao{internal.NewContentChannelDao()}
)

// Add your custom methods and functionality below.
