// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// contentImportCheckpointDao is the data access object for the table hg_content_import_checkpoint.
// You can define custom methods on it to extend its functionality as needed.
type contentImportCheckpointDao struct {
	*internal.ContentImportCheckpointDao
}

var (
	// ContentImportCheckpoint is a globally accessible object for table hg_content_import_checkpoint operations.
	ContentImportCheckpoint = contentImportCheckpointDao{internal.NewContentImportCheckpointDao()}
)

// Add your custom methods and functionality below.
