// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// contentImportRunDao is the data access object for the table hg_content_import_run.
// You can define custom methods on it to extend its functionality as needed.
type contentImportRunDao struct {
	*internal.ContentImportRunDao
}

var (
	// ContentImportRun is a globally accessible object for table hg_content_import_run operations.
	ContentImportRun = contentImportRunDao{internal.NewContentImportRunDao()}
)

// Add your custom methods and functionality below.
