// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// contentProfileDao is the data access object for the table hg_content_profile.
// You can define custom methods on it to extend its functionality as needed.
type contentProfileDao struct {
	*internal.ContentProfileDao
}

var (
	// ContentProfile is a globally accessible object for table hg_content_profile operations.
	ContentProfile = contentProfileDao{internal.NewContentProfileDao()}
)

// Add your custom methods and functionality below.
